package com.workflow.orchestrator.agent.tools.subagent

/**
 * Tool name generation for dynamic subagents.
 *
 * Ported from Cline's SubagentToolName.ts — builds deterministic, length-bounded
 * tool names of the form `use_subagent_{sanitized_name}`.
 */
object SubagentToolName {
    private const val PREFIX = "use_subagent_"
    private const val MAX_LENGTH = 64

    /**
     * Sanitize an agent name for use in a tool identifier.
     *
     * Lowercases, replaces non-alphanumeric characters with `_`,
     * collapses consecutive underscores, and trims leading/trailing underscores.
     */
    fun sanitize(name: String): String {
        return name.trim()
            .lowercase()
            .replace(Regex("[^a-z0-9_]+"), "_")
            .replace(Regex("_+"), "_")
            .replace(Regex("^_+|_+$"), "")
    }

    /**
     * FNV-1a hash of [value], returned as a base-36 string.
     *
     * Uses 32-bit FNV-1a with unsigned interpretation for the final radix conversion.
     */
    fun hashString(value: String): String {
        var hash = 2166136261L.toInt()
        for (ch in value) {
            hash = hash xor ch.code
            hash = (hash.toLong() * 16777619L).toInt()
        }
        return (hash.toLong() and 0xFFFFFFFFL).toString(36)
    }

    /**
     * Build a tool name for the given [agentName].
     *
     * Format: `use_subagent_{sanitized}`. If the result exceeds [MAX_LENGTH],
     * the sanitized portion is truncated and a 6-char hash suffix is appended
     * to preserve uniqueness.
     */
    fun build(agentName: String): String {
        val sanitized = sanitize(agentName).ifEmpty { "agent" }
        val hashSuffix = hashString(agentName).take(6)
        val base = "$PREFIX$sanitized"
        if (base.length <= MAX_LENGTH) return base
        val maxBodyLength = MAX_LENGTH - PREFIX.length - hashSuffix.length - 1
        val body = sanitized.take(maxOf(1, maxBodyLength))
        val candidate = "${PREFIX}${body}_$hashSuffix"
        return if (candidate.length <= MAX_LENGTH) candidate else candidate.take(MAX_LENGTH)
    }

    /**
     * Returns `true` if [toolName] was generated by [build] (i.e. starts with the subagent prefix).
     */
    fun isSubagentToolName(toolName: String): Boolean = toolName.startsWith(PREFIX)
}
