package com.workflow.orchestrator.core.bitbucket

import com.intellij.openapi.extensions.ExtensionPointName
import com.intellij.openapi.project.Project
import kotlinx.coroutines.CoroutineScope

/**
 * Extension point for cross-module PR creation delegation.
 * Implemented by the :pullrequest module; consumed by :bamboo, :handover, and the agent
 * without a compile-time dependency on :pullrequest.
 *
 * [launch] is called on the EDT or a coroutine dispatcher chosen by the caller.
 * The implementation prefetches all required data (branches, tickets, reviewers),
 * then opens the Create PR dialog on the EDT. Callers that need to react to a
 * successful creation should subscribe to [WorkflowEvent.PullRequestCreated] via
 * EventBus — the dialog emits it from doOKAction().
 */
interface CreatePrLauncher {

    /**
     * Opens the PR creation flow for the current project.
     *
     * @param project                The active IntelliJ project.
     * @param scope                  Coroutine scope for async prefetch work inside the launcher.
     * @param autoGenerateDescription When true, the dialog automatically generates a PR description
     *                               on open (Build-tab behavior). When false (default), the
     *                               description field starts empty and the user clicks Generate
     *                               manually (PR-tab behavior).
     */
    fun launch(
        project: Project,
        scope: CoroutineScope,
        autoGenerateDescription: Boolean = false
    )

    companion object {
        val EP_NAME = ExtensionPointName.create<CreatePrLauncher>(
            "com.workflow.orchestrator.createPrLauncher"
        )

        /** Returns the first registered implementation, or null if none is registered yet. */
        fun getInstance(): CreatePrLauncher? = EP_NAME.extensionList.firstOrNull()
    }
}
