package com.workflow.orchestrator.document.pdf

import com.workflow.orchestrator.core.model.DocumentBlock
import org.apache.pdfbox.pdmodel.encryption.InvalidPasswordException
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertNotNull
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.assertThrows
import java.nio.file.Paths

/**
 * Accuracy-critical tests for [PdfTableExtractor].
 *
 * Fixture values are pinned to the exact content generated by `/tmp/gen_fixtures.py`
 * (committed to the corpus on 2026-04-30) and confirmed via [PdfProbeTest] output.
 */
class PdfTableExtractorTest {

    private val extractor = PdfTableExtractor()

    private fun fixture(name: String) =
        Paths.get(javaClass.classLoader.getResource("fixtures/$name")!!.toURI())

    // ── 1. Total table count ──────────────────────────────────────────────────

    @Test
    fun `spec-with-tables extracts exactly 3 tables total (2 on page 1, 1 on page 2)`() {
        val tables = extractor.extract(fixture("spec-with-tables.pdf"))

        assertEquals(3, tables.size, "Expected exactly 3 tables from spec-with-tables.pdf")

        val page1Tables = tables.filter { it.page == 1 }
        val page2Tables = tables.filter { it.page == 2 }
        assertEquals(2, page1Tables.size, "Expected 2 tables on page 1")
        assertEquals(1, page2Tables.size, "Expected 1 table on page 2")
    }

    // ── 2. FR Matrix (table 0) — cell-perfect accuracy ───────────────────────

    @Test
    fun `spec-with-tables FR Matrix table has correct headers and 4 data rows`() {
        val tables = extractor.extract(fixture("spec-with-tables.pdf"))

        // FR Matrix is first table (page 1, topmost).
        val frTable = tables.first { it.page == 1 && it.block.headers == listOf("ReqId", "Priority", "Status") }
        assertNotNull(frTable, "FR Matrix table must be present")

        assertEquals(
            listOf("ReqId", "Priority", "Status"),
            frTable.block.headers,
            "FR Matrix headers must be [ReqId, Priority, Status]",
        )
        assertEquals(4, frTable.block.rows.size, "FR Matrix must have 4 data rows")
        assertEquals(
            listOf("FR-001", "MUST", "Approved"),
            frTable.block.rows[0],
            "FR Matrix row 0 must be [FR-001, MUST, Approved]",
        )
    }

    // ── 3. NFR table (table 1) ───────────────────────────────────────────────

    @Test
    fun `spec-with-tables NFR table has correct headers and 3 data rows`() {
        val tables = extractor.extract(fixture("spec-with-tables.pdf"))

        val nfrTable = tables.first { it.page == 1 && it.block.headers == listOf("Metric", "Bound", "Measured") }
        assertNotNull(nfrTable, "NFR table must be present")

        assertEquals(
            listOf("Metric", "Bound", "Measured"),
            nfrTable.block.headers,
            "NFR headers must be [Metric, Bound, Measured]",
        )
        assertEquals(3, nfrTable.block.rows.size, "NFR table must have 3 data rows")
    }

    // ── 4. Acceptance table (table 2, page 2) ────────────────────────────────

    @Test
    fun `spec-with-tables Acceptance table on page 2 has correct headers and 3 data rows`() {
        val tables = extractor.extract(fixture("spec-with-tables.pdf"))

        val acceptTable = tables.first { it.page == 2 }
        assertEquals(
            listOf("Test", "Expected", "Actual"),
            acceptTable.block.headers,
            "Acceptance headers must be [Test, Expected, Actual]",
        )
        assertEquals(3, acceptTable.block.rows.size, "Acceptance table must have 3 data rows")
    }

    // ── 5. Continuation detection — multi-page table merged into 1 ───────────

    @Test
    fun `multi-page-table merges into exactly 1 Table with 40 data rows`() {
        val tables = extractor.extract(fixture("multi-page-table.pdf"))

        assertEquals(
            1,
            tables.size,
            "multi-page-table.pdf must merge into exactly 1 Table after continuation detection, " +
                "got ${tables.size} tables with headers: ${tables.map { it.block.headers }}",
        )

        val merged = tables[0]
        assertEquals(
            listOf("BugId", "Severity", "Status"),
            merged.block.headers,
            "Merged table headers must be [BugId, Severity, Status]",
        )
        assertEquals(
            40,
            merged.block.rows.size,
            "Merged table must contain all 40 data rows; got ${merged.block.rows.size}",
        )
    }

    // ── 6. Multi-column PDF with lattice-only — no crash ─────────────────────

    @Test
    fun `tabula-multi-column with lattice-only does not crash`() {
        // Lattice may or may not find tables in a multi-column prose PDF; just assert no exception.
        val tables = extractor.extract(fixture("tabula-multi-column.pdf"))
        // Result may be empty — that is correct for a text-heavy multi-column PDF.
        assertNotNull(tables, "Result must not be null")
    }

    // ── 7. Stream mode enabled on a paragraph-heavy PDF — no crash ───────────

    @Test
    fun `enableStreamMode=true on spec-with-tables does not crash`() {
        val streamExtractor = PdfTableExtractor(enableStreamMode = true)
        // Tables count may vary with stream mode — we only assert no exception.
        val tables = streamExtractor.extract(fixture("spec-with-tables.pdf"))
        assertTrue(tables.isNotEmpty(), "Stream mode must still find the ruled tables")
    }

    // ── 8a. Phantom-table suppression on chart pages (Bug #16) ────────────────

    @Test
    fun `bar chart pages do not produce duplicate near-empty phantom tables`() {
        val tables = extractor.extract(fixture("tabula-eu-002.pdf"))
        // Page 2 of tabula-eu-002 is a bar chart; Tabula's lattice algorithm misclassifies
        // its axis ticks + bar boundaries as up to 8 overlapping tables. After phantom
        // filtering, very few (ideally zero) tables should remain on that page.
        val page2Tables = tables.filter { it.page == 2 }
        assertTrue(
            page2Tables.size < 5,
            "Page 2 is a chart; expected <5 detected tables, got ${page2Tables.size}",
        )
    }

    // ── 8b. Encrypted PDF bubbles InvalidPasswordException ────────────────────

    @Test
    fun `tabula-encrypted throws InvalidPasswordException`() {
        assertThrows<Exception> {
            extractor.extract(fixture("tabula-encrypted.pdf"))
        }.also { ex ->
            // Accept InvalidPasswordException or any PDFBox-flavoured password error.
            val isPasswordError = ex is InvalidPasswordException ||
                ex.cause is InvalidPasswordException ||
                ex.message?.contains("password", ignoreCase = true) == true ||
                ex.javaClass.name.contains("Encrypted", ignoreCase = true) ||
                ex.javaClass.name.contains("Password", ignoreCase = true)
            assertTrue(
                isPasswordError,
                "Expected an encryption/password exception, got: ${ex.javaClass.name}: ${ex.message}",
            )
        }
    }
}
