package com.workflow.orchestrator.pullrequest.ui

import com.intellij.ide.BrowserUtil
import com.intellij.openapi.application.EDT
import com.intellij.openapi.application.ModalityState
import com.intellij.openapi.application.invokeLater as platformInvokeLater
import com.intellij.openapi.diagnostic.Logger
import com.intellij.openapi.project.Project
import com.intellij.openapi.ui.DialogWrapper
import com.intellij.openapi.ui.ValidationInfo
import com.intellij.openapi.util.Disposer
import com.intellij.openapi.util.IconLoader
import com.intellij.ui.AnimatedIcon
import com.intellij.ui.JBColor
import com.intellij.ui.components.JBLabel
import com.intellij.ui.components.JBScrollPane
import com.intellij.ui.components.JBTextArea
import com.intellij.ui.components.JBTextField
import com.intellij.ui.components.fields.ExtendableTextComponent
import com.intellij.ui.components.fields.ExtendableTextField
import com.intellij.util.ui.JBUI
import com.workflow.orchestrator.core.ai.TextGenerationService
import com.workflow.orchestrator.core.bitbucket.BitbucketBranchClient
import com.workflow.orchestrator.core.bitbucket.BitbucketUser
import com.workflow.orchestrator.core.events.EventBus
import com.workflow.orchestrator.core.events.WorkflowEvent
import com.workflow.orchestrator.core.model.ApiResult
import com.workflow.orchestrator.core.settings.PluginSettings
import com.workflow.orchestrator.core.ui.StatusColors
import com.workflow.orchestrator.core.workflow.JiraTicketProvider
import com.workflow.orchestrator.core.workflow.TicketContext
import com.workflow.orchestrator.core.workflow.TicketTransition
import com.workflow.orchestrator.pullrequest.action.CreatePrContext
import com.workflow.orchestrator.pullrequest.action.RepoPrefetch
import com.workflow.orchestrator.pullrequest.service.MarkdownToHtml
import com.workflow.orchestrator.pullrequest.service.PrDescriptionGenerator
import git4idea.repo.GitRepositoryManager
import kotlinx.coroutines.CancellationException
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.Job
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import kotlinx.coroutines.withTimeoutOrNull
import java.awt.BorderLayout
import java.awt.CardLayout
import java.awt.Component
import java.awt.Cursor
import java.awt.Dimension
import java.awt.FlowLayout
import java.awt.Font
import java.awt.GridBagConstraints
import java.awt.GridBagLayout
import javax.swing.BorderFactory
import javax.swing.Box
import javax.swing.BoxLayout
import javax.swing.JButton
import javax.swing.JCheckBox
import javax.swing.JComboBox
import javax.swing.JComponent
import javax.swing.JEditorPane
import javax.swing.JMenuItem
import javax.swing.JPanel
import javax.swing.JPopupMenu
import javax.swing.JSeparator
import javax.swing.ScrollPaneConstants
import javax.swing.Timer
import javax.swing.event.DocumentEvent
import javax.swing.event.DocumentListener
import javax.swing.event.HyperlinkEvent

/**
 * Modal dialog for creating a pull request on Bitbucket.
 *
 * Phase 5 update — lives in :pullrequest so it can be launched via the
 * [com.workflow.orchestrator.core.bitbucket.CreatePrLauncher] EP from any feature module.
 *
 * Phase 9 update — adds multi-module (multi-Git-root) support:
 *  - A module slot at the top: static JBLabel for single repo, ComboBox for multiple.
 *  - Changing the selected module updates source label, target default, remote branches list.
 *  - PR submit uses the selected repo's projectKey/repoSlug via BitbucketBranchClient.forRepo.
 *
 * Features:
 *  - Searchable target branch
 *  - Multi-ticket input via [TicketChipInput] (max 5 chips, primary drives title + transition)
 *  - AI-generated markdown description with Edit/Preview tabs and provenance footer
 *  - Optional inline AI title generation — gated by `PluginSettings.enableAiTitleGeneration`
 *  - Reviewer autocomplete from Bitbucket users API
 *  - Optional Jira ticket transition
 *  - `autoGenerateDescription` flag — Build-tab callers keep the legacy auto-generate on open;
 *    future PR-tab callers (Phase 6) pass `false` for a manual-generate UX
 */
class CreatePrDialog(
    private val project: Project,
    private val scope: CoroutineScope,
    private val context: CreatePrContext,
    private val autoGenerateDescription: Boolean = true
) : DialogWrapper(project, true) {

    private val log = Logger.getInstance(CreatePrDialog::class.java)
    private val settings = PluginSettings.getInstance(project)

    // Multi-repo state — mutable when user changes the module combo
    private var currentRepo: RepoPrefetch = context.repos[context.initialSelectedRepoIndex]

    // Convenience alias — derived from currentRepo
    private val sourceBranch: String get() = currentRepo.sourceBranch

    // Source label — updated when module changes
    private val sourceBranchLabel = JBLabel(currentRepo.sourceBranch).apply {
        foreground = StatusColors.LINK
    }

    // Module selector (only visible for multi-repo).
    // Long repo labels (e.g. "name (PROJ/very-long-repo-slug)") would otherwise blow out the
    // combo's preferred width and push the dialog into horizontal scroll. Cap with a
    // prototype string that reflects a realistic max label length.
    private val moduleCombo: JComboBox<RepoComboItem>? = if (context.repos.size > 1) {
        JComboBox<RepoComboItem>().also { combo ->
            context.repos.forEach { r -> combo.addItem(RepoComboItem(r)) }
            combo.selectedIndex = context.initialSelectedRepoIndex
            combo.prototypeDisplayValue = RepoComboItem(context.repos[0])
            combo.maximumSize = Dimension(JBUI.scale(480), combo.preferredSize.height)
        }
    } else null

    // Target branch — free-text field + a chevron that opens a searchable list popup
    // (IntelliJ's JBPopupFactory). The field remains manually editable so advanced users
    // can paste/type a branch name directly. 28 cols keeps the field narrow so long branch
    // names don't push the dialog into horizontal scroll.
    private val targetField: ExtendableTextField = ExtendableTextField(28).apply {
        text = currentRepo.defaultTarget
    }

    // Tickets (primary + up to 4 linked)
    private val ticketChipInput = TicketChipInput(
        project = project,
        scope = scope,
        initialKeys = context.initialTicketKeys,
        initialContexts = context.initialTicketContexts,
        onChange = { _ -> onTicketsChanged() }
    )

    // Title — ExtendableTextField only if AI title generation is enabled, else plain field.
    // Both are typed as JBTextField so the rest of the dialog code is uniform.
    private val aiTitleEnabled = settings.state.enableAiTitleGeneration
    private val titleField: JBTextField = if (aiTitleEnabled) {
        ExtendableTextField(40).apply { text = context.defaultTitle }
    } else {
        JBTextField(40).apply { text = context.defaultTitle }
    }
    private var aiTitleExtension: ExtendableTextComponent.Extension? = null
    private var titleGenJob: Job? = null

    // Description
    private val descriptionArea = JBTextArea(10, 50).apply {
        lineWrap = true; wrapStyleWord = true
        font = JBUI.Fonts.create(com.intellij.openapi.editor.colors.EditorColorsManager.getInstance().globalScheme.editorFontName, 12)
    }
    private val previewPane = JEditorPane().apply {
        isEditable = false
        contentType = "text/html"
        addHyperlinkListener { e ->
            if (e.eventType == HyperlinkEvent.EventType.ACTIVATED) {
                BrowserUtil.browse(e.url)
            }
        }
    }
    private val descCardLayout = CardLayout()
    private val descCardPanel = JPanel(descCardLayout)
    private val editTabButton = JButton("Edit")
    private val previewTabButton = JButton("Preview")
    private val regenerateButton = JButton("⟳ Generate")
    private val descLoadingLabel = JBLabel("Generating description...").apply {
        icon = AnimatedIcon.Default()
    }
    private val descEmptyLabel = JBLabel("Select target branch and click Generate to produce a description.").apply {
        foreground = StatusColors.SECONDARY_TEXT
    }
    private val provenanceLabel = JBLabel("").apply {
        foreground = StatusColors.SECONDARY_TEXT
        font = font.deriveFont(font.size2D - 1f)
    }
    private var descriptionGenJob: Job? = null
    private var lastGen: GenContext? = null
    /** Incremented on every module change and generation start to detect write-after-cancel races. */
    private var descriptionGenerationId: Int = 0

    // Reviewers
    private val reviewerChipsPanel = JPanel(FlowLayout(FlowLayout.LEFT, JBUI.scale(4), JBUI.scale(2)))
    private val reviewerInput = JBTextField(15)
    private val reviewerPopup = JPopupMenu()
    private val selectedReviewers = mutableListOf<String>()
    /** username → chip component for chips that came from the current repo's Bitbucket defaults.
     *  Used by [onModuleChanged] to swap repo-level chips without touching manual additions. */
    private val repoDefaultReviewerChips = mutableMapOf<String, JPanel>()
    private var userSearchJob: Job? = null

    // Transition
    private val transitionCheckbox = JCheckBox("Transition ticket to").apply { isSelected = true }
    private val transitionCombo = JComboBox<TransitionItem>()

    // Result
    private val resultLabel = JBLabel("")
    private val titleErrorLabel = JBLabel("").apply {
        foreground = JBColor.RED
        font = font.deriveFont(font.size2D - 1f)
        isVisible = false
    }

    init {
        title = "Create Pull Request"
        setOKButtonText("Create PR")
        init()

        // Register the chip widget for disposal so its timer-backed icons are released.
        Disposer.register(disposable, ticketChipInput)

        // AI title extension (gated by settings).
        if (aiTitleEnabled && titleField is ExtendableTextField) {
            val icon = IconLoader.getIcon("/icons/ai-sparkle.svg", CreatePrDialog::class.java)
            val ext = ExtendableTextComponent.Extension.create(
                icon, icon, "Generate title with AI"
            ) { onAiTitleClicked() }
            aiTitleExtension = ext
            (titleField as ExtendableTextField).addExtension(ext)
        }

        // Target branch dropdown chevron — opens a searchable JBPopup list (filterable by
        // typing, click/Enter to select, Esc to close). IntelliJ's standard pattern; replaces
        // the previous JPopupMenu-based autocomplete which had several UX problems: the
        // popup had no filter field, item clicks sometimes failed to propagate when opened
        // from an ExtendableTextField icon, and the DocumentListener kept re-spawning the
        // popup while the user was trying to dismiss it.
        val chevron = com.intellij.icons.AllIcons.General.ArrowDown
        targetField.addExtension(
            ExtendableTextComponent.Extension.create(chevron, chevron, "Show branches") {
                showBranchChooser()
            }
        )

        // Pre-fill reviewers: union of settings-configured defaults AND the selected repo's
        // Bitbucket-configured default reviewers (from the default-reviewers plugin, fetched
        // during prefetch). Track which usernames came from the repo-level list so we can
        // swap them out if the user changes modules without clobbering manually-added chips.
        val initialReviewers = (context.defaultReviewers + currentRepo.repoDefaultReviewers).distinct()
        initialReviewers.forEach { addReviewerChip(it, fromRepoDefaults = it in currentRepo.repoDefaultReviewers) }

        // Populate transitions
        if (context.transitions.isNotEmpty() && context.initialTicketKeys.isNotEmpty()) {
            context.transitions.forEach { transitionCombo.addItem(TransitionItem(it)) }
            val reviewIdx = context.transitions.indexOfFirst {
                it.name.contains("Review", ignoreCase = true) ||
                    it.name.contains("In Review", ignoreCase = true)
            }
            if (reviewIdx >= 0) transitionCombo.selectedIndex = reviewIdx
        } else {
            transitionCheckbox.isVisible = false
            transitionCombo.isVisible = false
        }

        // Wire module combo selection change
        moduleCombo?.addActionListener {
            val selected = moduleCombo.selectedItem as? RepoComboItem ?: return@addActionListener
            if (selected.repoPrefetch != currentRepo) {
                onModuleChanged(selected.repoPrefetch)
            }
        }

        // Wire provenance invalidation only — target-branch autocomplete-while-typing was
        // removed along with the old JPopupMenu approach. Users now discover branches via
        // the chevron dropdown; free text in the field remains valid (git push/PR endpoint
        // validates it server-side).
        targetField.document.addDocumentListener(object : DocumentListener {
            override fun insertUpdate(e: DocumentEvent) = onTargetChanged()
            override fun removeUpdate(e: DocumentEvent) = onTargetChanged()
            override fun changedUpdate(e: DocumentEvent) = onTargetChanged()
        })

        // Wire reviewer search
        reviewerInput.document.addDocumentListener(object : DocumentListener {
            override fun insertUpdate(e: DocumentEvent) = searchUsers()
            override fun removeUpdate(e: DocumentEvent) = searchUsers()
            override fun changedUpdate(e: DocumentEvent) = searchUsers()
        })

        // Wire description tabs
        editTabButton.addActionListener { showDescriptionTab("edit") }
        previewTabButton.addActionListener { showDescriptionTab("preview") }
        regenerateButton.addActionListener { generateDescription() }

        transitionCheckbox.addActionListener {
            transitionCombo.isEnabled = transitionCheckbox.isSelected
        }

        // Default target is already resolved per-repo in prefetch (currentRepo.defaultTarget).
        // The field is initialized there; no async resolution needed here.

        // Description: auto-generate on open for Build tab; empty-state for PR tab.
        if (autoGenerateDescription) {
            generateDescription()
        } else {
            showDescriptionEmpty()
        }
    }

    override fun dispose() {
        descriptionGenJob?.cancel()
        titleGenJob?.cancel()
        userSearchJob?.cancel()
        super.dispose()
    }

    /**
     * Post a runnable to the EDT at this dialog's modality level.
     *
     * Critical: the IntelliJ `invokeLater` default from a background thread resolves to
     * `ModalityState.NON_MODAL`, which is suspended while any modal dialog is open —
     * including this dialog. Any background-thread → EDT hop inside a modal coroutine
     * (LLM title/description generation, user/branch search, etc.) MUST use this helper,
     * otherwise the runnable is queued but never dispatched and the UI spins forever.
     *
     * `stateForComponent(contentPane)` is evaluated lazily so construction-time callers
     * (before createCenterPanel builds the content pane) also work — we fall back to
     * `ModalityState.any()` until the pane is realized.
     */
    private fun invokeLater(runnable: Runnable) {
        val cp = this.contentPane
        val modality = if (cp != null) ModalityState.stateForComponent(cp) else ModalityState.any()
        platformInvokeLater(modality) { runnable.run() }
    }

    override fun createCenterPanel(): JComponent {
        val panel = JPanel(BorderLayout(0, JBUI.scale(8)))
        panel.preferredSize = Dimension(JBUI.scale(620), JBUI.scale(580))
        panel.border = JBUI.Borders.empty(12)

        val content = JPanel().apply {
            layout = BoxLayout(this, BoxLayout.Y_AXIS)
        }

        // Module slot (above Source/Target)
        val branchPanel = JPanel(GridBagLayout())
        val gbc = GridBagConstraints().apply { fill = GridBagConstraints.HORIZONTAL; insets = JBUI.insets(3, 0) }

        var nextRow = 0

        if (context.repos.size == 1) {
            val singleRepo = context.repos[0]
            val labelText = buildRepoLabel(singleRepo)
            gbc.gridx = 0; gbc.gridy = nextRow; gbc.weightx = 0.0
            branchPanel.add(JBLabel("Module:").apply { border = JBUI.Borders.emptyRight(8) }, gbc)
            gbc.gridx = 1; gbc.weightx = 1.0
            // Truncate visually via tooltip for very long labels so column 1 doesn't grow
            // past the dialog width. Full label is still available on hover.
            branchPanel.add(JBLabel(labelText).apply {
                toolTipText = labelText
                maximumSize = Dimension(JBUI.scale(480), preferredSize.height)
            }, gbc)
            nextRow++
        } else if (moduleCombo != null) {
            gbc.gridx = 0; gbc.gridy = nextRow; gbc.weightx = 0.0
            branchPanel.add(JBLabel("Module:").apply { border = JBUI.Borders.emptyRight(8) }, gbc)
            gbc.gridx = 1; gbc.weightx = 1.0
            branchPanel.add(moduleCombo, gbc)
            nextRow++
        }

        gbc.gridx = 0; gbc.gridy = nextRow; gbc.weightx = 0.0
        branchPanel.add(JBLabel("Source:").apply { border = JBUI.Borders.emptyRight(8) }, gbc)
        gbc.gridx = 1; gbc.weightx = 1.0
        branchPanel.add(sourceBranchLabel, gbc)
        nextRow++

        gbc.gridx = 0; gbc.gridy = nextRow; gbc.weightx = 0.0
        branchPanel.add(JBLabel("Target:").apply { border = JBUI.Borders.emptyRight(8) }, gbc)
        gbc.gridx = 1; gbc.weightx = 1.0
        targetField.maximumSize = Dimension(JBUI.scale(480), targetField.preferredSize.height)
        branchPanel.add(targetField, gbc)

        content.add(branchPanel)
        content.add(Box.createVerticalStrut(JBUI.scale(8)))

        // Tickets — sits between Target and Title, per Phase 5 spec.
        content.add(JBLabel("Tickets").apply { foreground = StatusColors.SECONDARY_TEXT })
        content.add(Box.createVerticalStrut(JBUI.scale(4)))
        val ticketBorder = JPanel(BorderLayout()).apply {
            border = BorderFactory.createCompoundBorder(
                BorderFactory.createLineBorder(JBColor.border()),
                JBUI.Borders.empty(4)
            )
            add(ticketChipInput, BorderLayout.CENTER)
        }
        content.add(ticketBorder)
        content.add(Box.createVerticalStrut(JBUI.scale(8)))
        content.add(JSeparator())
        content.add(Box.createVerticalStrut(JBUI.scale(8)))

        // Title
        content.add(JBLabel("Title").apply { foreground = StatusColors.SECONDARY_TEXT })
        content.add(Box.createVerticalStrut(JBUI.scale(4)))
        content.add(titleField)
        content.add(titleErrorLabel)
        content.add(Box.createVerticalStrut(JBUI.scale(8)))

        // Description with Edit/Preview tabs
        val descHeader = JPanel(BorderLayout()).apply {
            add(JBLabel("Description").apply { foreground = StatusColors.SECONDARY_TEXT }, BorderLayout.WEST)
            val tabButtons = JPanel(FlowLayout(FlowLayout.RIGHT, JBUI.scale(4), 0)).apply {
                add(editTabButton); add(previewTabButton); add(regenerateButton)
            }
            add(tabButtons, BorderLayout.EAST)
        }
        content.add(descHeader)
        content.add(Box.createVerticalStrut(JBUI.scale(4)))

        descCardPanel.add(JBScrollPane(descriptionArea), "edit")
        descCardPanel.add(JBScrollPane(previewPane), "preview")
        descCardPanel.add(createLoadingPanel(), "loading")
        descCardPanel.add(createEmptyPanel(), "empty")
        descCardPanel.preferredSize = Dimension(0, JBUI.scale(200))
        content.add(descCardPanel)
        content.add(Box.createVerticalStrut(JBUI.scale(2)))
        content.add(provenanceLabel)
        content.add(Box.createVerticalStrut(JBUI.scale(8)))

        // Reviewers
        content.add(JBLabel("Reviewers").apply { foreground = StatusColors.SECONDARY_TEXT })
        content.add(Box.createVerticalStrut(JBUI.scale(4)))
        val reviewerPanel = JPanel(BorderLayout()).apply {
            border = BorderFactory.createCompoundBorder(
                BorderFactory.createLineBorder(JBColor.border()),
                JBUI.Borders.empty(4)
            )
            add(reviewerChipsPanel, BorderLayout.CENTER)
        }
        reviewerChipsPanel.add(reviewerInput)
        content.add(reviewerPanel)
        content.add(JBLabel("Type to search Bitbucket users").apply {
            foreground = StatusColors.INFO; font = font.deriveFont(font.size2D - 2f)
        })
        content.add(Box.createVerticalStrut(JBUI.scale(8)))
        content.add(JSeparator())
        content.add(Box.createVerticalStrut(JBUI.scale(8)))

        // Transition
        val transPanel = JPanel(FlowLayout(FlowLayout.LEFT, JBUI.scale(6), 0))
        transPanel.add(transitionCheckbox)
        transPanel.add(transitionCombo)
        content.add(transPanel)
        content.add(Box.createVerticalStrut(JBUI.scale(4)))
        content.add(resultLabel)

        panel.add(JBScrollPane(content).apply {
            border = null
            verticalScrollBarPolicy = ScrollPaneConstants.VERTICAL_SCROLLBAR_AS_NEEDED
        }, BorderLayout.CENTER)

        return panel
    }

    private fun createLoadingPanel(): JPanel = JPanel(BorderLayout()).apply {
        add(JPanel().apply {
            layout = BoxLayout(this, BoxLayout.Y_AXIS)
            add(Box.createVerticalGlue())
            add(descLoadingLabel.apply { alignmentX = Component.CENTER_ALIGNMENT })
            add(Box.createVerticalGlue())
        }, BorderLayout.CENTER)
    }

    private fun createEmptyPanel(): JPanel = JPanel(BorderLayout()).apply {
        add(JPanel().apply {
            layout = BoxLayout(this, BoxLayout.Y_AXIS)
            add(Box.createVerticalGlue())
            add(descEmptyLabel.apply { alignmentX = Component.CENTER_ALIGNMENT })
            add(Box.createVerticalGlue())
        }, BorderLayout.CENTER)
    }

    // --- Module selection ---

    private fun onModuleChanged(newRepo: RepoPrefetch) {
        currentRepo = newRepo
        // Update source label
        sourceBranchLabel.text = newRepo.sourceBranch
        // Reset target to new repo's default. The branch chooser popup is ephemeral
        // (rebuilt per open from currentRepo.remoteBranches) so no cleanup is needed.
        targetField.text = newRepo.defaultTarget
        // Swap repo-level default reviewer chips for the new repo. Manually-added chips
        // (not in repoDefaultReviewerChips) and settings-based chips are preserved.
        val existingRepoDefaults = repoDefaultReviewerChips.toMap()
        existingRepoDefaults.forEach { (username, chip) ->
            selectedReviewers.remove(username)
            reviewerChipsPanel.remove(chip)
        }
        repoDefaultReviewerChips.clear()
        newRepo.repoDefaultReviewers.forEach { username ->
            if (username !in selectedReviewers) addReviewerChip(username, fromRepoDefaults = true)
        }
        reviewerChipsPanel.revalidate()
        reviewerChipsPanel.repaint()
        // Invalidate description — increment the generation counter so any in-flight
        // invokeLater writes from the cancelled job can detect they are stale and discard.
        descriptionGenerationId++
        descriptionGenJob?.cancel()
        titleGenJob?.cancel()
        provenanceLabel.text = ""
        lastGen = null
        showDescriptionEmpty()
    }

    private fun buildRepoLabel(repo: RepoPrefetch): String {
        val key = repo.config.bitbucketProjectKey.orEmpty()
        val slug = repo.config.bitbucketRepoSlug.orEmpty()
        val name = repo.config.name.orEmpty().ifBlank { slug }
        return if (key.isNotBlank() && slug.isNotBlank()) "$name ($key/$slug)" else name
    }

    // --- Branch search ---

    /**
     * Open a searchable branch-chooser popup for the currently selected module. Uses
     * `JBPopupFactory.createPopupChooserBuilder` — IntelliJ's standard pattern for
     * filter-as-you-type list popups. Built-in speed-search filters the list by substring;
     * click or Enter commits the selected branch into [targetField]; Esc or click-away
     * closes the popup.
     */
    private fun showBranchChooser() {
        val branches = currentRepo.remoteBranches
        if (branches.isEmpty() || !targetField.isShowing) return
        val popup = com.intellij.openapi.ui.popup.JBPopupFactory.getInstance()
            .createPopupChooserBuilder(branches)
            .setTitle("Select target branch")
            .setNamerForFiltering { it }
            .setRequestFocus(true)
            .setMovable(false)
            .setResizable(true)
            .setSelectedValue(targetField.text, true)
            .setItemChosenCallback { chosen ->
                if (chosen != null) targetField.text = chosen
            }
            .createPopup()
        popup.showUnderneathOf(targetField)
    }

    // --- Reviewer autocomplete ---

    private fun searchUsers() {
        val text = reviewerInput.text.trim()
        if (text.length < 2) {
            reviewerPopup.isVisible = false
            return
        }
        userSearchJob?.cancel()
        // Use the currently-selected repo's Bitbucket config so multi-repo projects query the
        // right Bitbucket instance (fromConfiguredSettings() always picks the primary repo).
        val repoAtSearch = currentRepo
        userSearchJob = scope.launch {
            delay(300)
            val client = BitbucketBranchClient.forRepo(repoAtSearch.config)
                ?: BitbucketBranchClient.fromConfiguredSettings()
                ?: run {
                    log.warn("[Pr:CreateDialog] No Bitbucket client for reviewer search (repo='${repoAtSearch.config.displayLabel}')")
                    return@launch
                }
            when (val result = client.getUsers(text)) {
                is ApiResult.Success -> invokeLater {
                    // Show all matches — already-selected users will simply be filtered from
                    // the dropdown items (they stay selectable only once). If the entire
                    // result is already-selected we still want the popup to hide cleanly.
                    showUserResults(result.data.filter { it.name !in selectedReviewers })
                }
                is ApiResult.Error -> {
                    log.warn("[Pr:CreateDialog] User search failed: ${result.message}")
                }
            }
        }
    }

    private fun showUserResults(users: List<BitbucketUser>) {
        reviewerPopup.removeAll()
        if (users.isEmpty()) {
            reviewerPopup.isVisible = false
            return
        }
        // Async guard: if the dialog was closed between the coroutine's invokeLater
        // submission and EDT dispatch, reviewerInput may no longer be on screen.
        // JPopupMenu.show() resolves the invoker's screen location and throws
        // IllegalComponentStateException when the component isn't showing.
        if (!reviewerInput.isShowing) {
            reviewerPopup.isVisible = false
            return
        }
        users.forEach { user ->
            val label = "${user.name} — ${user.displayName}"
            val item = JMenuItem(label)
            item.addActionListener {
                addReviewerChip(user.name)
                reviewerInput.text = ""
                reviewerPopup.isVisible = false
            }
            reviewerPopup.add(item)
        }
        // pack() so the popup sizes to the new items — without this, Swing can paint the
        // popup at the previous (possibly empty) size and the items render invisibly.
        reviewerPopup.pack()
        reviewerPopup.show(reviewerInput, 0, reviewerInput.height)
    }

    private fun addReviewerChip(username: String, fromRepoDefaults: Boolean = false) {
        if (username in selectedReviewers) return
        selectedReviewers.add(username)
        val chip = JPanel(FlowLayout(FlowLayout.LEFT, JBUI.scale(4), 0)).apply {
            background = StatusColors.CARD_BG
            border = JBUI.Borders.empty(1, 6)
            add(JBLabel(username).apply { font = font.deriveFont(11f) })
            val removeBtn = JBLabel("✕").apply {
                cursor = Cursor.getPredefinedCursor(Cursor.HAND_CURSOR)
                foreground = StatusColors.SECONDARY_TEXT
            }
            removeBtn.addMouseListener(object : java.awt.event.MouseAdapter() {
                override fun mouseClicked(e: java.awt.event.MouseEvent?) {
                    selectedReviewers.remove(username)
                    repoDefaultReviewerChips.remove(username)
                    reviewerChipsPanel.remove(this@apply)
                    reviewerChipsPanel.revalidate()
                    reviewerChipsPanel.repaint()
                }
            })
            add(removeBtn)
        }
        if (fromRepoDefaults) repoDefaultReviewerChips[username] = chip
        reviewerChipsPanel.remove(reviewerInput)
        reviewerChipsPanel.add(chip)
        reviewerChipsPanel.add(reviewerInput)
        reviewerChipsPanel.revalidate()
    }

    // --- Description ---

    private fun showDescriptionTab(tab: String) {
        if (tab == "preview") {
            previewPane.text = MarkdownToHtml.convert(descriptionArea.text)
        }
        descCardLayout.show(descCardPanel, tab)
        editTabButton.font = editTabButton.font.deriveFont(if (tab == "edit") Font.BOLD else Font.PLAIN)
        previewTabButton.font = previewTabButton.font.deriveFont(if (tab == "preview") Font.BOLD else Font.PLAIN)
    }

    private fun showDescriptionLoading() {
        descCardLayout.show(descCardPanel, "loading")
        regenerateButton.isEnabled = false
    }

    private fun showDescriptionEmpty() {
        descCardLayout.show(descCardPanel, "empty")
        descriptionArea.text = ""
        provenanceLabel.text = ""
        lastGen = null
        regenerateButton.isEnabled = true
    }

    private fun generateDescription() {
        descriptionGenJob?.cancel()
        // Capture the generation ID at launch time. Any in-flight write that races a
        // subsequent onModuleChanged() will detect the counter has moved and discard.
        val myId = ++descriptionGenerationId
        descriptionGenJob = scope.launch {
            val (targetBranch, tickets, repoAtGenTime) = withContext(Dispatchers.EDT) {
                Triple(targetField.text.trim(), ticketChipInput.allValid(), currentRepo)
            }
            invokeLater { showDescriptionLoading() }
            try {
                // Materialise the GitRepository for the selected repo so PrDescriptionGenerator
                // targets the correct git root when running git log / diff.
                val gitRepo = GitRepositoryManager.getInstance(project).repositories
                    .find { it.root.path == repoAtGenTime.config.localVcsRootPath }

                if (gitRepo == null) {
                    log.warn("[Pr:CreateDialog] No GitRepository found for path '${repoAtGenTime.config.localVcsRootPath}' — cannot generate description")
                    invokeLater {
                        if (myId != descriptionGenerationId) return@invokeLater
                        showDescriptionEmpty()
                        regenerateButton.isEnabled = true
                    }
                    return@launch
                }

                val description = withTimeoutOrNull(120_000) {
                    PrDescriptionGenerator.generate(project, gitRepo, tickets, repoAtGenTime.sourceBranch, targetBranch)
                }
                if (description == null) {
                    log.warn("[Pr:CreateDialog] generate description timed out")
                    invokeLater {
                        if (myId != descriptionGenerationId) return@invokeLater
                        showDescriptionEmpty()
                        regenerateButton.isEnabled = true
                    }
                    return@launch
                }
                invokeLater {
                    if (myId != descriptionGenerationId) return@invokeLater
                    descriptionArea.text = description
                    showDescriptionTab("edit")
                    regenerateButton.isEnabled = true
                    lastGen = GenContext(targetBranch, tickets.map { it.key })
                    updateProvenanceLabel()
                }
            } catch (e: CancellationException) {
                invokeLater {
                    if (myId != descriptionGenerationId) return@invokeLater
                    if (descriptionArea.text.isBlank()) showDescriptionEmpty()
                    else showDescriptionTab("edit")
                    regenerateButton.isEnabled = true
                }
                throw e
            } catch (e: Exception) {
                log.warn("[Pr:CreateDialog] generate description failed", e)
                invokeLater {
                    if (myId != descriptionGenerationId) return@invokeLater
                    showDescriptionEmpty()
                    regenerateButton.isEnabled = true
                }
            }
        }
    }

    private fun updateProvenanceLabel() {
        provenanceLabel.text = buildProvenanceText(
            lastGen,
            targetField.text.trim(),
            ticketChipInput.allValid().map { it.key }
        )
    }

    private fun onTargetChanged() {
        if (lastGen != null) updateProvenanceLabel()
    }

    private fun onTicketsChanged() {
        if (lastGen != null) updateProvenanceLabel()
    }

    // --- AI title generation ---

    private fun onAiTitleClicked() {
        val existing = titleGenJob
        if (existing != null && existing.isActive) {
            existing.cancel()
            restoreTitleField()
            return
        }
        val primary = ticketChipInput.validPrimary()
        if (primary == null) {
            flashTitleError("Need a valid primary ticket to generate a title")
            return
        }
        swapTitleExtensionToSpinner()
        titleField.isEditable = false
        titleErrorLabel.isVisible = false

        titleGenJob = scope.launch {
            val textGen = TextGenerationService.getInstance()
            try {
                val result: String? = withTimeoutOrNull(120_000) {
                    try {
                        textGen?.generatePrTitle(project, primary, emptyList())
                    } catch (e: Exception) {
                        log.warn("[PR:Create] AI title generation failed: ${e.message}")
                        null
                    }
                }
                invokeLater {
                    restoreTitleField()
                    if (!result.isNullOrBlank()) {
                        titleField.text = result.trim()
                    } else {
                        flashTitleError("Could not generate title — try again")
                    }
                }
            } catch (e: CancellationException) {
                invokeLater { restoreTitleField() }
                throw e
            }
        }
    }

    private fun swapTitleExtensionToSpinner() {
        val field = titleField as? ExtendableTextField ?: return
        val current = aiTitleExtension ?: return
        field.removeExtension(current)
        val spinner = AnimatedIcon.Default()
        val spinnerExt = ExtendableTextComponent.Extension.create(
            spinner, spinner, "Generating — click to cancel"
        ) { onAiTitleClicked() }
        aiTitleExtension = spinnerExt
        field.addExtension(spinnerExt)
    }

    private fun restoreTitleField() {
        titleField.isEditable = true
        val field = titleField as? ExtendableTextField ?: return
        val current = aiTitleExtension
        if (current != null) field.removeExtension(current)
        val icon = IconLoader.getIcon("/icons/ai-sparkle.svg", CreatePrDialog::class.java)
        val restored = ExtendableTextComponent.Extension.create(
            icon, icon, "Generate title with AI"
        ) { onAiTitleClicked() }
        aiTitleExtension = restored
        field.addExtension(restored)
    }

    private fun flashTitleError(msg: String) {
        titleErrorLabel.text = msg
        titleErrorLabel.isVisible = true
        val timer = Timer(3000) {
            titleErrorLabel.isVisible = false
            titleErrorLabel.text = ""
        }
        timer.isRepeats = false
        timer.start()
    }

    // --- Validation ---

    override fun doValidate(): ValidationInfo? {
        val validTickets = ticketChipInput.allValid()
        if (validTickets.isEmpty()) {
            return ValidationInfo("At least one valid Jira ticket required", ticketChipInput)
        }
        if (titleField.text.isBlank()) return ValidationInfo("Title cannot be empty", titleField)
        if (targetField.text.isBlank()) return ValidationInfo("Select a target branch", targetField)
        if (targetField.text == currentRepo.sourceBranch) return ValidationInfo("Target cannot be the same as source", targetField)
        return null
    }

    // --- Submit ---

    override fun doOKAction() {
        isOKActionEnabled = false
        resultLabel.text = "Creating PR..."
        resultLabel.foreground = JBColor.foreground()

        // Use the selected repo's config rather than the single-value PluginSettings fields.
        val repoForSubmit = currentRepo
        val projectKey = repoForSubmit.config.bitbucketProjectKey.orEmpty()
        val repoSlug = repoForSubmit.config.bitbucketRepoSlug.orEmpty()

        val client = BitbucketBranchClient.forRepo(repoForSubmit.config)
        if (client == null) {
            resultLabel.text = "Bitbucket not configured"
            resultLabel.foreground = JBColor.RED
            isOKActionEnabled = true
            return
        }

        val reviewers = selectedReviewers.map {
            com.workflow.orchestrator.core.bitbucket.BitbucketReviewer(
                com.workflow.orchestrator.core.bitbucket.BitbucketReviewerUser(it)
            )
        }

        val primary = ticketChipInput.validPrimary()

        scope.launch {
            val result = client.createPullRequest(
                projectKey = projectKey,
                repoSlug = repoSlug,
                title = titleField.text.trim(),
                description = descriptionArea.text,
                fromBranch = repoForSubmit.sourceBranch,
                toBranch = targetField.text.trim(),
                reviewers = reviewers
            )

            invokeLater {
                when (result) {
                    is ApiResult.Success -> {
                        val prUrl = result.data.links.self.firstOrNull()?.href ?: ""
                        log.info("[PR:Create] PR #${result.data.id} created: $prUrl")

                        if (transitionCheckbox.isSelected && transitionCheckbox.isVisible && primary != null) {
                            val selected = transitionCombo.selectedItem as? TransitionItem
                            if (selected != null) {
                                scope.launch {
                                    JiraTicketProvider.getInstance()
                                        ?.transitionTicket(primary.key, selected.transition.id)
                                }
                            }
                        }

                        val ticketId = primary?.key ?: settings.state.activeTicketId.orEmpty()
                        scope.launch {
                            project.getService(EventBus::class.java)
                                .emit(WorkflowEvent.PullRequestCreated(prUrl, result.data.id, ticketId))
                        }

                        close(OK_EXIT_CODE)
                    }
                    is ApiResult.Error -> {
                        isOKActionEnabled = true
                        resultLabel.text = result.message
                        resultLabel.foreground = JBColor.RED
                    }
                }
            }
        }
    }

    /** Internal: last successful generation context, used by the provenance label. */
    internal data class GenContext(val target: String, val tickets: List<String>)

    companion object {
        /**
         * Pure helper for the provenance label text — exposed for unit tests.
         *
         * - Returns `""` when no generation has happened yet.
         * - Otherwise returns a base string with target + tickets, plus a
         *   "(target changed…)" / "(tickets changed…)" suffix when the current
         *   UI state diverges from the last generation.
         */
        internal fun buildProvenanceText(
            lastGen: GenContext?,
            currentTarget: String,
            currentTickets: List<String>
        ): String {
            val g = lastGen ?: return ""
            val ticketsLabel = if (g.tickets.isEmpty()) "(none)" else g.tickets.joinToString(",")
            val base = "Generated against target: ${g.target} · tickets: $ticketsLabel"
            val suffix = buildString {
                if (currentTarget != g.target) append(" · (target changed — click Generate to refresh)")
                if (currentTickets != g.tickets) append(" · (tickets changed — click Generate to refresh)")
            }
            return base + suffix
        }
    }
}

private data class TransitionItem(val transition: TicketTransition) {
    override fun toString() = transition.name
}

private data class RepoComboItem(val repoPrefetch: RepoPrefetch) {
    override fun toString(): String {
        val key = repoPrefetch.config.bitbucketProjectKey.orEmpty()
        val slug = repoPrefetch.config.bitbucketRepoSlug.orEmpty()
        val name = repoPrefetch.config.name.orEmpty().ifBlank { slug }
        return if (key.isNotBlank() && slug.isNotBlank()) "$name ($key/$slug)" else name
    }
}
