package com.workflow.orchestrator.pullrequest.ui

import com.intellij.ide.BrowserUtil
import com.intellij.openapi.application.EDT
import com.intellij.openapi.application.invokeLater
import com.intellij.openapi.diagnostic.Logger
import com.intellij.openapi.project.Project
import com.intellij.openapi.ui.DialogWrapper
import com.intellij.openapi.ui.ValidationInfo
import com.intellij.openapi.util.Disposer
import com.intellij.openapi.util.IconLoader
import com.intellij.ui.AnimatedIcon
import com.intellij.ui.JBColor
import com.intellij.ui.components.JBLabel
import com.intellij.ui.components.JBScrollPane
import com.intellij.ui.components.JBTextArea
import com.intellij.ui.components.JBTextField
import com.intellij.ui.components.fields.ExtendableTextComponent
import com.intellij.ui.components.fields.ExtendableTextField
import com.intellij.util.ui.JBUI
import com.workflow.orchestrator.core.ai.TextGenerationService
import com.workflow.orchestrator.core.bitbucket.BitbucketBranchClient
import com.workflow.orchestrator.core.bitbucket.BitbucketUser
import com.workflow.orchestrator.core.events.EventBus
import com.workflow.orchestrator.core.events.WorkflowEvent
import com.workflow.orchestrator.core.model.ApiResult
import com.workflow.orchestrator.core.settings.PluginSettings
import com.workflow.orchestrator.core.ui.StatusColors
import com.workflow.orchestrator.core.util.DefaultBranchResolver
import com.workflow.orchestrator.core.workflow.JiraTicketProvider
import com.workflow.orchestrator.core.workflow.TicketContext
import com.workflow.orchestrator.core.workflow.TicketTransition
import com.workflow.orchestrator.pullrequest.service.MarkdownToHtml
import com.workflow.orchestrator.pullrequest.service.PrDescriptionGenerator
import git4idea.repo.GitRepositoryManager
import kotlinx.coroutines.CancellationException
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.Job
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import kotlinx.coroutines.withTimeoutOrNull
import java.awt.BorderLayout
import java.awt.CardLayout
import java.awt.Component
import java.awt.Cursor
import java.awt.Dimension
import java.awt.FlowLayout
import java.awt.Font
import java.awt.GridBagConstraints
import java.awt.GridBagLayout
import javax.swing.BorderFactory
import javax.swing.Box
import javax.swing.BoxLayout
import javax.swing.JButton
import javax.swing.JCheckBox
import javax.swing.JComboBox
import javax.swing.JComponent
import javax.swing.JEditorPane
import javax.swing.JMenuItem
import javax.swing.JPanel
import javax.swing.JPopupMenu
import javax.swing.JSeparator
import javax.swing.ScrollPaneConstants
import javax.swing.Timer
import javax.swing.event.DocumentEvent
import javax.swing.event.DocumentListener
import javax.swing.event.HyperlinkEvent

/**
 * Modal dialog for creating a pull request on Bitbucket.
 *
 * Phase 5 update — lives in :pullrequest so it can be launched via the
 * [com.workflow.orchestrator.core.bitbucket.CreatePrLauncher] EP from any feature module.
 *
 * Features:
 *  - Searchable target branch
 *  - Multi-ticket input via [TicketChipInput] (max 5 chips, primary drives title + transition)
 *  - AI-generated markdown description with Edit/Preview tabs and provenance footer
 *  - Optional inline AI title generation — gated by `PluginSettings.enableAiTitleGeneration`
 *  - Reviewer autocomplete from Bitbucket users API
 *  - Optional Jira ticket transition
 *  - `autoGenerateDescription` flag — Build-tab callers keep the legacy auto-generate on open;
 *    future PR-tab callers (Phase 6) pass `false` for a manual-generate UX
 */
class CreatePrDialog(
    private val project: Project,
    private val scope: CoroutineScope,
    private val sourceBranch: String,
    private val remoteBranches: List<String>,
    private val initialTicketKeys: List<String>,
    private val initialTicketContexts: Map<String, TicketContext>,
    private val transitions: List<TicketTransition>,
    private val defaultTitle: String,
    private val defaultReviewers: List<String>,
    private val autoGenerateDescription: Boolean = true
) : DialogWrapper(project, true) {

    private val log = Logger.getInstance(CreatePrDialog::class.java)
    private val settings = PluginSettings.getInstance(project)

    // Target branch
    private val targetField = JBTextField().apply {
        text = "develop" // async-resolved below in init
    }
    private val branchPopup = JPopupMenu()

    // Tickets (primary + up to 4 linked)
    private val ticketChipInput = TicketChipInput(
        project = project,
        scope = scope,
        initialKeys = initialTicketKeys,
        initialContexts = initialTicketContexts,
        onChange = { _ -> onTicketsChanged() }
    )

    // Title — ExtendableTextField only if AI title generation is enabled, else plain field.
    // Both are typed as JBTextField so the rest of the dialog code is uniform.
    private val aiTitleEnabled = settings.state.enableAiTitleGeneration
    private val titleField: JBTextField = if (aiTitleEnabled) {
        ExtendableTextField(40).apply { text = defaultTitle }
    } else {
        JBTextField(40).apply { text = defaultTitle }
    }
    private var aiTitleExtension: ExtendableTextComponent.Extension? = null
    private var titleGenJob: Job? = null

    // Description
    private val descriptionArea = JBTextArea(10, 50).apply {
        lineWrap = true; wrapStyleWord = true
        font = JBUI.Fonts.create(com.intellij.openapi.editor.colors.EditorColorsManager.getInstance().globalScheme.editorFontName, 12)
    }
    private val previewPane = JEditorPane().apply {
        isEditable = false
        contentType = "text/html"
        addHyperlinkListener { e ->
            if (e.eventType == HyperlinkEvent.EventType.ACTIVATED) {
                BrowserUtil.browse(e.url)
            }
        }
    }
    private val descCardLayout = CardLayout()
    private val descCardPanel = JPanel(descCardLayout)
    private val editTabButton = JButton("Edit")
    private val previewTabButton = JButton("Preview")
    private val regenerateButton = JButton("⟳ Generate")
    private val descLoadingLabel = JBLabel("Generating description...").apply {
        icon = AnimatedIcon.Default()
    }
    private val descEmptyLabel = JBLabel("Select target branch and click Generate to produce a description.").apply {
        foreground = StatusColors.SECONDARY_TEXT
    }
    private val provenanceLabel = JBLabel("").apply {
        foreground = StatusColors.SECONDARY_TEXT
        font = font.deriveFont(font.size2D - 1f)
    }
    private var descriptionGenJob: Job? = null
    private var lastGen: GenContext? = null

    // Reviewers
    private val reviewerChipsPanel = JPanel(FlowLayout(FlowLayout.LEFT, JBUI.scale(4), JBUI.scale(2)))
    private val reviewerInput = JBTextField(15)
    private val reviewerPopup = JPopupMenu()
    private val selectedReviewers = mutableListOf<String>()
    private var userSearchJob: Job? = null

    // Transition
    private val transitionCheckbox = JCheckBox("Transition ticket to").apply { isSelected = true }
    private val transitionCombo = JComboBox<TransitionItem>()

    // Result
    private val resultLabel = JBLabel("")
    private val titleErrorLabel = JBLabel("").apply {
        foreground = JBColor.RED
        font = font.deriveFont(font.size2D - 1f)
        isVisible = false
    }

    init {
        title = "Create Pull Request"
        setOKButtonText("Create PR")
        init()

        // Register the chip widget for disposal so its timer-backed icons are released.
        Disposer.register(disposable, ticketChipInput)

        // AI title extension (gated by settings).
        if (aiTitleEnabled && titleField is ExtendableTextField) {
            val icon = IconLoader.getIcon("/icons/ai-sparkle.svg", CreatePrDialog::class.java)
            val ext = ExtendableTextComponent.Extension.create(
                icon, icon, "Generate title with AI"
            ) { onAiTitleClicked() }
            aiTitleExtension = ext
            (titleField as ExtendableTextField).addExtension(ext)
        }

        // Pre-fill reviewers
        defaultReviewers.forEach { addReviewerChip(it) }

        // Populate transitions
        if (transitions.isNotEmpty() && initialTicketKeys.isNotEmpty()) {
            transitions.forEach { transitionCombo.addItem(TransitionItem(it)) }
            val reviewIdx = transitions.indexOfFirst {
                it.name.contains("Review", ignoreCase = true) ||
                    it.name.contains("In Review", ignoreCase = true)
            }
            if (reviewIdx >= 0) transitionCombo.selectedIndex = reviewIdx
        } else {
            transitionCheckbox.isVisible = false
            transitionCombo.isVisible = false
        }

        // Wire target branch search + provenance invalidation
        targetField.document.addDocumentListener(object : DocumentListener {
            override fun insertUpdate(e: DocumentEvent) { filterBranches(); onTargetChanged() }
            override fun removeUpdate(e: DocumentEvent) { filterBranches(); onTargetChanged() }
            override fun changedUpdate(e: DocumentEvent) { onTargetChanged() }
        })

        // Wire reviewer search
        reviewerInput.document.addDocumentListener(object : DocumentListener {
            override fun insertUpdate(e: DocumentEvent) = searchUsers()
            override fun removeUpdate(e: DocumentEvent) = searchUsers()
            override fun changedUpdate(e: DocumentEvent) = searchUsers()
        })

        // Wire description tabs
        editTabButton.addActionListener { showDescriptionTab("edit") }
        previewTabButton.addActionListener { showDescriptionTab("preview") }
        regenerateButton.addActionListener { generateDescription() }

        transitionCheckbox.addActionListener {
            transitionCombo.isEnabled = transitionCheckbox.isSelected
        }

        // Resolve default target branch asynchronously
        scope.launch {
            val repos = GitRepositoryManager.getInstance(project).repositories
            val repo = repos.firstOrNull()
            val resolvedTarget = repo?.let { DefaultBranchResolver.getInstance(project).resolve(it) } ?: "develop"
            invokeLater { if (targetField.text == "develop") targetField.text = resolvedTarget }
        }

        // Description: auto-generate on open for Build tab; empty-state for PR tab.
        if (autoGenerateDescription) {
            generateDescription()
        } else {
            showDescriptionEmpty()
        }
    }

    override fun dispose() {
        descriptionGenJob?.cancel()
        titleGenJob?.cancel()
        super.dispose()
    }

    override fun createCenterPanel(): JComponent {
        val panel = JPanel(BorderLayout(0, JBUI.scale(8)))
        panel.preferredSize = Dimension(JBUI.scale(620), JBUI.scale(580))
        panel.border = JBUI.Borders.empty(12)

        val content = JPanel().apply {
            layout = BoxLayout(this, BoxLayout.Y_AXIS)
        }

        // Source & Target
        val branchPanel = JPanel(GridBagLayout())
        val gbc = GridBagConstraints().apply { fill = GridBagConstraints.HORIZONTAL; insets = JBUI.insets(3, 0) }

        gbc.gridx = 0; gbc.gridy = 0; gbc.weightx = 0.0
        branchPanel.add(JBLabel("Source:").apply { border = JBUI.Borders.emptyRight(8) }, gbc)
        gbc.gridx = 1; gbc.weightx = 1.0
        branchPanel.add(JBLabel(sourceBranch).apply { foreground = StatusColors.LINK }, gbc)

        gbc.gridx = 0; gbc.gridy = 1; gbc.weightx = 0.0
        branchPanel.add(JBLabel("Target:").apply { border = JBUI.Borders.emptyRight(8) }, gbc)
        gbc.gridx = 1; gbc.weightx = 1.0
        branchPanel.add(targetField, gbc)

        content.add(branchPanel)
        content.add(Box.createVerticalStrut(JBUI.scale(8)))

        // Tickets — sits between Target and Title, per Phase 5 spec.
        content.add(JBLabel("Tickets").apply { foreground = StatusColors.SECONDARY_TEXT })
        content.add(Box.createVerticalStrut(JBUI.scale(4)))
        val ticketBorder = JPanel(BorderLayout()).apply {
            border = BorderFactory.createCompoundBorder(
                BorderFactory.createLineBorder(JBColor.border()),
                JBUI.Borders.empty(4)
            )
            add(ticketChipInput, BorderLayout.CENTER)
        }
        content.add(ticketBorder)
        content.add(Box.createVerticalStrut(JBUI.scale(8)))
        content.add(JSeparator())
        content.add(Box.createVerticalStrut(JBUI.scale(8)))

        // Title
        content.add(JBLabel("Title").apply { foreground = StatusColors.SECONDARY_TEXT })
        content.add(Box.createVerticalStrut(JBUI.scale(4)))
        content.add(titleField)
        content.add(titleErrorLabel)
        content.add(Box.createVerticalStrut(JBUI.scale(8)))

        // Description with Edit/Preview tabs
        val descHeader = JPanel(BorderLayout()).apply {
            add(JBLabel("Description").apply { foreground = StatusColors.SECONDARY_TEXT }, BorderLayout.WEST)
            val tabButtons = JPanel(FlowLayout(FlowLayout.RIGHT, JBUI.scale(4), 0)).apply {
                add(editTabButton); add(previewTabButton); add(regenerateButton)
            }
            add(tabButtons, BorderLayout.EAST)
        }
        content.add(descHeader)
        content.add(Box.createVerticalStrut(JBUI.scale(4)))

        descCardPanel.add(JBScrollPane(descriptionArea), "edit")
        descCardPanel.add(JBScrollPane(previewPane), "preview")
        descCardPanel.add(createLoadingPanel(), "loading")
        descCardPanel.add(createEmptyPanel(), "empty")
        descCardPanel.preferredSize = Dimension(0, JBUI.scale(200))
        content.add(descCardPanel)
        content.add(Box.createVerticalStrut(JBUI.scale(2)))
        content.add(provenanceLabel)
        content.add(Box.createVerticalStrut(JBUI.scale(8)))

        // Reviewers
        content.add(JBLabel("Reviewers").apply { foreground = StatusColors.SECONDARY_TEXT })
        content.add(Box.createVerticalStrut(JBUI.scale(4)))
        val reviewerPanel = JPanel(BorderLayout()).apply {
            border = BorderFactory.createCompoundBorder(
                BorderFactory.createLineBorder(JBColor.border()),
                JBUI.Borders.empty(4)
            )
            add(reviewerChipsPanel, BorderLayout.CENTER)
        }
        reviewerChipsPanel.add(reviewerInput)
        content.add(reviewerPanel)
        content.add(JBLabel("Type to search Bitbucket users").apply {
            foreground = StatusColors.INFO; font = font.deriveFont(font.size2D - 2f)
        })
        content.add(Box.createVerticalStrut(JBUI.scale(8)))
        content.add(JSeparator())
        content.add(Box.createVerticalStrut(JBUI.scale(8)))

        // Transition
        val transPanel = JPanel(FlowLayout(FlowLayout.LEFT, JBUI.scale(6), 0))
        transPanel.add(transitionCheckbox)
        transPanel.add(transitionCombo)
        content.add(transPanel)
        content.add(Box.createVerticalStrut(JBUI.scale(4)))
        content.add(resultLabel)

        panel.add(JBScrollPane(content).apply {
            border = null
            verticalScrollBarPolicy = ScrollPaneConstants.VERTICAL_SCROLLBAR_AS_NEEDED
        }, BorderLayout.CENTER)

        return panel
    }

    private fun createLoadingPanel(): JPanel = JPanel(BorderLayout()).apply {
        add(JPanel().apply {
            layout = BoxLayout(this, BoxLayout.Y_AXIS)
            add(Box.createVerticalGlue())
            add(descLoadingLabel.apply { alignmentX = Component.CENTER_ALIGNMENT })
            add(Box.createVerticalGlue())
        }, BorderLayout.CENTER)
    }

    private fun createEmptyPanel(): JPanel = JPanel(BorderLayout()).apply {
        add(JPanel().apply {
            layout = BoxLayout(this, BoxLayout.Y_AXIS)
            add(Box.createVerticalGlue())
            add(descEmptyLabel.apply { alignmentX = Component.CENTER_ALIGNMENT })
            add(Box.createVerticalGlue())
        }, BorderLayout.CENTER)
    }

    // --- Branch search ---

    private fun filterBranches() {
        val text = targetField.text.lowercase()
        branchPopup.removeAll()
        val matches = remoteBranches.filter { it.lowercase().contains(text) }.take(15)
        if (matches.isEmpty() || (matches.size == 1 && matches[0] == targetField.text)) {
            branchPopup.isVisible = false
            return
        }
        matches.forEach { branch ->
            val item = JMenuItem(branch)
            item.addActionListener {
                targetField.text = branch
                branchPopup.isVisible = false
            }
            branchPopup.add(item)
        }
        branchPopup.show(targetField, 0, targetField.height)
    }

    // --- Reviewer autocomplete ---

    private fun searchUsers() {
        val text = reviewerInput.text.trim()
        if (text.length < 2) {
            reviewerPopup.isVisible = false
            return
        }
        userSearchJob?.cancel()
        userSearchJob = scope.launch {
            delay(300)
            val client = BitbucketBranchClient.fromConfiguredSettings() ?: return@launch
            val result = client.getUsers(text)
            invokeLater {
                if (result is ApiResult.Success) {
                    showUserResults(result.data.filter { it.name !in selectedReviewers })
                }
            }
        }
    }

    private fun showUserResults(users: List<BitbucketUser>) {
        reviewerPopup.removeAll()
        if (users.isEmpty()) {
            reviewerPopup.isVisible = false
            return
        }
        users.forEach { user ->
            val label = "${user.name} — ${user.displayName}"
            val item = JMenuItem(label)
            item.addActionListener {
                addReviewerChip(user.name)
                reviewerInput.text = ""
                reviewerPopup.isVisible = false
            }
            reviewerPopup.add(item)
        }
        reviewerPopup.show(reviewerInput, 0, reviewerInput.height)
    }

    private fun addReviewerChip(username: String) {
        if (username in selectedReviewers) return
        selectedReviewers.add(username)
        val chip = JPanel(FlowLayout(FlowLayout.LEFT, JBUI.scale(4), 0)).apply {
            background = StatusColors.CARD_BG
            border = JBUI.Borders.empty(1, 6)
            add(JBLabel(username).apply { font = font.deriveFont(11f) })
            val removeBtn = JBLabel("✕").apply {
                cursor = Cursor.getPredefinedCursor(Cursor.HAND_CURSOR)
                foreground = StatusColors.SECONDARY_TEXT
            }
            removeBtn.addMouseListener(object : java.awt.event.MouseAdapter() {
                override fun mouseClicked(e: java.awt.event.MouseEvent?) {
                    selectedReviewers.remove(username)
                    reviewerChipsPanel.remove(this@apply)
                    reviewerChipsPanel.revalidate()
                    reviewerChipsPanel.repaint()
                }
            })
            add(removeBtn)
        }
        reviewerChipsPanel.remove(reviewerInput)
        reviewerChipsPanel.add(chip)
        reviewerChipsPanel.add(reviewerInput)
        reviewerChipsPanel.revalidate()
    }

    // --- Description ---

    private fun showDescriptionTab(tab: String) {
        if (tab == "preview") {
            previewPane.text = MarkdownToHtml.convert(descriptionArea.text)
        }
        descCardLayout.show(descCardPanel, tab)
        editTabButton.font = editTabButton.font.deriveFont(if (tab == "edit") Font.BOLD else Font.PLAIN)
        previewTabButton.font = previewTabButton.font.deriveFont(if (tab == "preview") Font.BOLD else Font.PLAIN)
    }

    private fun showDescriptionLoading() {
        descCardLayout.show(descCardPanel, "loading")
        regenerateButton.isEnabled = false
    }

    private fun showDescriptionEmpty() {
        descCardLayout.show(descCardPanel, "empty")
        descriptionArea.text = ""
        provenanceLabel.text = ""
        lastGen = null
        regenerateButton.isEnabled = true
    }

    private fun generateDescription() {
        descriptionGenJob?.cancel()
        descriptionGenJob = scope.launch {
            val targetBranch = withContext(Dispatchers.EDT) { targetField.text.trim() }
            val tickets = ticketChipInput.allValid()
            invokeLater { showDescriptionLoading() }
            try {
                val description = withTimeoutOrNull(120_000) {
                    PrDescriptionGenerator.generate(project, tickets, sourceBranch, targetBranch)
                }
                if (description == null) {
                    log.warn("[Pr:CreateDialog] generate description timed out")
                    invokeLater {
                        showDescriptionEmpty()
                        regenerateButton.isEnabled = true
                    }
                    return@launch
                }
                invokeLater {
                    descriptionArea.text = description
                    showDescriptionTab("edit")
                    regenerateButton.isEnabled = true
                    lastGen = GenContext(targetBranch, tickets.map { it.key })
                    updateProvenanceLabel()
                }
            } catch (e: CancellationException) {
                invokeLater {
                    if (descriptionArea.text.isBlank()) showDescriptionEmpty()
                    else showDescriptionTab("edit")
                    regenerateButton.isEnabled = true
                }
                throw e
            } catch (e: Exception) {
                log.warn("[Pr:CreateDialog] generate description failed", e)
                invokeLater {
                    showDescriptionEmpty()
                    regenerateButton.isEnabled = true
                }
            }
        }
    }

    private fun updateProvenanceLabel() {
        provenanceLabel.text = buildProvenanceText(
            lastGen,
            targetField.text.trim(),
            ticketChipInput.allValid().map { it.key }
        )
    }

    private fun onTargetChanged() {
        if (lastGen != null) updateProvenanceLabel()
    }

    private fun onTicketsChanged() {
        if (lastGen != null) updateProvenanceLabel()
    }

    // --- AI title generation ---

    private fun onAiTitleClicked() {
        val existing = titleGenJob
        if (existing != null && existing.isActive) {
            existing.cancel()
            restoreTitleField()
            return
        }
        val primary = ticketChipInput.validPrimary()
        if (primary == null) {
            flashTitleError("Need a valid primary ticket to generate a title")
            return
        }
        swapTitleExtensionToSpinner()
        titleField.isEditable = false
        titleErrorLabel.isVisible = false

        titleGenJob = scope.launch {
            val textGen = TextGenerationService.getInstance()
            try {
                val result: String? = withTimeoutOrNull(120_000) {
                    try {
                        textGen?.generatePrTitle(project, primary, emptyList())
                    } catch (e: Exception) {
                        log.warn("[PR:Create] AI title generation failed: ${e.message}")
                        null
                    }
                }
                invokeLater {
                    restoreTitleField()
                    if (!result.isNullOrBlank()) {
                        titleField.text = result.trim()
                    } else {
                        flashTitleError("Could not generate title — try again")
                    }
                }
            } catch (e: CancellationException) {
                invokeLater { restoreTitleField() }
                throw e
            }
        }
    }

    private fun swapTitleExtensionToSpinner() {
        val field = titleField as? ExtendableTextField ?: return
        val current = aiTitleExtension ?: return
        field.removeExtension(current)
        val spinner = AnimatedIcon.Default()
        val spinnerExt = ExtendableTextComponent.Extension.create(
            spinner, spinner, "Generating — click to cancel"
        ) { onAiTitleClicked() }
        aiTitleExtension = spinnerExt
        field.addExtension(spinnerExt)
    }

    private fun restoreTitleField() {
        titleField.isEditable = true
        val field = titleField as? ExtendableTextField ?: return
        val current = aiTitleExtension
        if (current != null) field.removeExtension(current)
        val icon = IconLoader.getIcon("/icons/ai-sparkle.svg", CreatePrDialog::class.java)
        val restored = ExtendableTextComponent.Extension.create(
            icon, icon, "Generate title with AI"
        ) { onAiTitleClicked() }
        aiTitleExtension = restored
        field.addExtension(restored)
    }

    private fun flashTitleError(msg: String) {
        titleErrorLabel.text = msg
        titleErrorLabel.isVisible = true
        val timer = Timer(3000) {
            titleErrorLabel.isVisible = false
            titleErrorLabel.text = ""
        }
        timer.isRepeats = false
        timer.start()
    }

    // --- Validation ---

    override fun doValidate(): ValidationInfo? {
        val validTickets = ticketChipInput.allValid()
        if (validTickets.isEmpty()) {
            return ValidationInfo("At least one valid Jira ticket required", ticketChipInput)
        }
        if (titleField.text.isBlank()) return ValidationInfo("Title cannot be empty", titleField)
        if (targetField.text.isBlank()) return ValidationInfo("Select a target branch", targetField)
        if (targetField.text == sourceBranch) return ValidationInfo("Target cannot be the same as source", targetField)
        return null
    }

    // --- Submit ---

    override fun doOKAction() {
        isOKActionEnabled = false
        resultLabel.text = "Creating PR..."
        resultLabel.foreground = JBColor.foreground()

        val projectKey = settings.state.bitbucketProjectKey.orEmpty()
        val repoSlug = settings.state.bitbucketRepoSlug.orEmpty()

        val client = BitbucketBranchClient.fromConfiguredSettings()
        if (client == null) {
            resultLabel.text = "Bitbucket not configured"
            resultLabel.foreground = JBColor.RED
            isOKActionEnabled = true
            return
        }

        val reviewers = selectedReviewers.map {
            com.workflow.orchestrator.core.bitbucket.BitbucketReviewer(
                com.workflow.orchestrator.core.bitbucket.BitbucketReviewerUser(it)
            )
        }

        val primary = ticketChipInput.validPrimary()

        scope.launch {
            val result = client.createPullRequest(
                projectKey = projectKey,
                repoSlug = repoSlug,
                title = titleField.text.trim(),
                description = descriptionArea.text,
                fromBranch = sourceBranch,
                toBranch = targetField.text.trim(),
                reviewers = reviewers
            )

            invokeLater {
                when (result) {
                    is ApiResult.Success -> {
                        val prUrl = result.data.links.self.firstOrNull()?.href ?: ""
                        log.info("[PR:Create] PR #${result.data.id} created: $prUrl")

                        if (transitionCheckbox.isSelected && transitionCheckbox.isVisible && primary != null) {
                            val selected = transitionCombo.selectedItem as? TransitionItem
                            if (selected != null) {
                                scope.launch {
                                    JiraTicketProvider.getInstance()
                                        ?.transitionTicket(primary.key, selected.transition.id)
                                }
                            }
                        }

                        val ticketId = primary?.key ?: settings.state.activeTicketId.orEmpty()
                        scope.launch {
                            project.getService(EventBus::class.java)
                                .emit(WorkflowEvent.PullRequestCreated(prUrl, result.data.id, ticketId))
                        }

                        close(OK_EXIT_CODE)
                    }
                    is ApiResult.Error -> {
                        isOKActionEnabled = true
                        resultLabel.text = result.message
                        resultLabel.foreground = JBColor.RED
                    }
                }
            }
        }
    }

    /** Internal: last successful generation context, used by the provenance label. */
    internal data class GenContext(val target: String, val tickets: List<String>)

    companion object {
        /**
         * Pure helper for the provenance label text — exposed for unit tests.
         *
         * - Returns `""` when no generation has happened yet.
         * - Otherwise returns a base string with target + tickets, plus a
         *   "(target changed…)" / "(tickets changed…)" suffix when the current
         *   UI state diverges from the last generation.
         */
        internal fun buildProvenanceText(
            lastGen: GenContext?,
            currentTarget: String,
            currentTickets: List<String>
        ): String {
            val g = lastGen ?: return ""
            val ticketsLabel = if (g.tickets.isEmpty()) "(none)" else g.tickets.joinToString(",")
            val base = "Generated against target: ${g.target} · tickets: $ticketsLabel"
            val suffix = buildString {
                if (currentTarget != g.target) append(" · (target changed — click Generate to refresh)")
                if (currentTickets != g.tickets) append(" · (tickets changed — click Generate to refresh)")
            }
            return base + suffix
        }
    }
}

private data class TransitionItem(val transition: TicketTransition) {
    override fun toString() = transition.name
}
