package com.workflow.orchestrator.core.http

import com.intellij.openapi.diagnostic.Logger
import com.workflow.orchestrator.core.ai.dto.ChatMessage
import kotlinx.serialization.encodeToString
import kotlinx.serialization.json.Json
import java.io.File
import java.io.FileOutputStream
import java.io.OutputStreamWriter
import java.nio.charset.StandardCharsets

/**
 * Writes the raw (pre-sanitize) message list to disk before
 * [com.workflow.orchestrator.core.ai.SourcegraphChatClient.sanitizeMessages] is called.
 *
 * The file `{reqId}.pre-sanitize.json` is stored alongside the `.request.http` and
 * `.response.http` files so a developer can diff "what we intended to send" versus
 * "what we actually sent after sanitization".
 *
 * This helper is called from `SourcegraphChatClient.sendMessage()` and
 * `SourcegraphChatClient.sendMessageStream()` before their `sanitizeMessages()` call,
 * only when [RawApiTraceConfig.shouldTrace] returns true.
 */
object PreSanitizeDumper {

    private val log = Logger.getInstance(PreSanitizeDumper::class.java)

    private val json = Json {
        prettyPrint = true
        ignoreUnknownKeys = true
        encodeDefaults = true
        explicitNulls = false
    }

    /**
     * Serialize [messages] to pretty-printed JSON and write to
     * `{traceDir}/{reqId}.pre-sanitize.json`.
     *
     * No-ops on any I/O or serialization error (logs at debug level).
     *
     * @param messages  The raw message list before sanitization.
     * @param reqId     The trace ID assigned by [RawApiTraceInterceptor] (or generated by the
     *                  caller). This is also injected as `X-Workflow-Trace-Id` so all three
     *                  files are correlated.
     * @param traceDir  The dated directory to write into. Created if absent.
     */
    fun dump(messages: List<ChatMessage>, reqId: String, traceDir: File) {
        try {
            traceDir.mkdirs()
            val file = File(traceDir, "$reqId.pre-sanitize.json")
            val payload = json.encodeToString(messages)
            OutputStreamWriter(FileOutputStream(file), StandardCharsets.UTF_8).use { w ->
                w.write(payload)
            }
            log.debug("[RawTrace] Pre-sanitize dump: ${file.name} (${messages.size} messages)")
        } catch (e: Exception) {
            log.debug("[RawTrace] Pre-sanitize dump failed: ${e.message}")
        }
    }
}
