package com.workflow.orchestrator.core.http

import com.intellij.openapi.diagnostic.Logger
import com.workflow.orchestrator.core.ai.dto.ChatMessage
import com.workflow.orchestrator.core.util.OwnerOnlyFile
import kotlinx.serialization.encodeToString
import kotlinx.serialization.json.Json
import java.io.File
import java.io.FileOutputStream
import java.io.OutputStreamWriter
import java.nio.charset.StandardCharsets

/**
 * Writes the raw (pre-sanitize) message list to disk before
 * [com.workflow.orchestrator.core.ai.SourcegraphChatClient.sanitizeMessages] is called.
 *
 * The file `{reqId}.pre-sanitize.json` is stored alongside the `.request.http` and
 * `.response.http` files so a developer can diff "what we intended to send" versus
 * "what we actually sent after sanitization".
 *
 * This helper is called from `SourcegraphChatClient.sendMessage()` and
 * `SourcegraphChatClient.sendMessageStream()` before their `sanitizeMessages()` call,
 * only when [RawApiTraceConfig.shouldTrace] returns true.
 *
 * The serialized JSON is always passed through [textRedactor] before writing
 * (audit finding core:F-4). Pass [PromptBodyRedactor::redact] at call sites, or a
 * stronger literal-token-aware redactor when the token is available at call time.
 */
object PreSanitizeDumper {

    private val log = Logger.getInstance(PreSanitizeDumper::class.java)

    private val json = Json {
        prettyPrint = true
        ignoreUnknownKeys = true
        encodeDefaults = true
        explicitNulls = false
    }

    /**
     * Serialize [messages] to pretty-printed JSON, apply [textRedactor], and write to
     * `{traceDir}/{reqId}.pre-sanitize.json`.
     *
     * No-ops on any I/O or serialization error (logs at debug level).
     *
     * @param messages      The raw message list before sanitization.
     * @param reqId         The trace ID assigned by [RawApiTraceInterceptor] (or generated by the
     *                      caller). Also injected as `X-Workflow-Trace-Id` to correlate files.
     * @param traceDir      The dated directory to write into. Created if absent.
     * @param textRedactor  Applied to the serialized JSON before writing. Defaults to
     *                      [PromptBodyRedactor::redact]; pass a stronger literal-token redactor
     *                      when the configured token is available.
     */
    fun dump(
        messages: List<ChatMessage>,
        reqId: String,
        traceDir: File,
        textRedactor: (String) -> String = PromptBodyRedactor::redact,
    ) {
        try {
            traceDir.mkdirs()
            OwnerOnlyFile.restrictDir(traceDir)  // A4: dump dir holds full (redacted) request bodies
            val file = File(traceDir, "$reqId.pre-sanitize.json")
            val payload = textRedactor(json.encodeToString(messages))
            OutputStreamWriter(FileOutputStream(file), StandardCharsets.UTF_8).use { w ->
                w.write(payload)
            }
            OwnerOnlyFile.restrictFile(file)
            log.debug("[RawTrace] Pre-sanitize dump: ${file.name} (${messages.size} messages)")
        } catch (e: Exception) {
            log.debug("[RawTrace] Pre-sanitize dump failed: ${e.message}")
        }
    }
}
