package com.workflow.orchestrator.pullrequest.action

import com.intellij.openapi.application.invokeLater
import com.intellij.openapi.diagnostic.Logger
import com.intellij.openapi.project.Project
import com.intellij.openapi.ui.Messages
import com.workflow.orchestrator.core.bitbucket.CreatePrLauncher
import com.workflow.orchestrator.pullrequest.ui.CreatePrDialog
import kotlinx.coroutines.CancellationException
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.launch

/**
 * Phase 6 implementation of the [CreatePrLauncher] extension point.
 *
 * Runs [CreatePrPrefetch] on a background coroutine to collect source branch,
 * remote branches, ticket contexts, transitions, default title, and reviewers.
 * On success, opens [CreatePrDialog] on the EDT.  On prefetch failure (Bitbucket
 * not configured, no Git branch), shows a warning dialog instead.
 *
 * Registered in plugin.xml under the `com.workflow.orchestrator.createPrLauncher`
 * extension point.  Callers that need to react to a successful PR creation should
 * subscribe to [com.workflow.orchestrator.core.events.WorkflowEvent.PullRequestCreated]
 * on the [com.workflow.orchestrator.core.events.EventBus] — the dialog emits it
 * from doOKAction().
 */
class CreatePrLauncherImpl : CreatePrLauncher {

    private val log = Logger.getInstance(CreatePrLauncherImpl::class.java)

    override fun launch(
        project: Project,
        scope: CoroutineScope,
        autoGenerateDescription: Boolean
    ) {
        scope.launch {
            val result = try {
                CreatePrPrefetch.run(project)
            } catch (e: CancellationException) {
                throw e   // honor cancel
            } catch (e: Exception) {
                log.warn("[PR:Launcher] Prefetch failed unexpectedly", e)
                invokeLater {
                    Messages.showWarningDialog(
                        project,
                        "Could not prepare PR creation: ${e.message ?: "unknown error"}",
                        "Create Pull Request"
                    )
                }
                return@launch
            }
            when (result) {
                is PrefetchResult.Failure -> {
                    log.warn("[PR:Launcher] Prefetch failed: ${result.message}")
                    invokeLater {
                        Messages.showWarningDialog(
                            project,
                            result.message,
                            "Create Pull Request"
                        )
                    }
                }
                is PrefetchResult.Success -> {
                    val ctx = result.context
                    log.info("[PR:Launcher] Prefetch OK — branch='${ctx.sourceBranch}'" +
                        " remoteBranches=${ctx.remoteBranches.size}" +
                        " tickets=${ctx.initialTicketKeys}" +
                        " reviewers=${ctx.defaultReviewers.size}" +
                        " autoGen=$autoGenerateDescription")
                    invokeLater {
                        val dialog = CreatePrDialog(
                            project = project,
                            scope = scope,
                            sourceBranch = ctx.sourceBranch,
                            remoteBranches = ctx.remoteBranches,
                            initialTicketKeys = ctx.initialTicketKeys,
                            initialTicketContexts = ctx.initialTicketContexts,
                            transitions = ctx.transitions,
                            defaultTitle = ctx.defaultTitle,
                            defaultReviewers = ctx.defaultReviewers,
                            autoGenerateDescription = autoGenerateDescription
                        )
                        dialog.showAndGet()
                        // PullRequestCreated event is emitted from CreatePrDialog.doOKAction().
                        // Callers (PrDashboardPanel, PrBar) subscribe to EventBus for refresh.
                    }
                }
            }
        }
    }
}
