package com.workflow.orchestrator.agent.tools.framework.endpoints

import com.intellij.ide.scratch.ScratchRootType
import com.intellij.lang.Language
import com.intellij.openapi.application.ReadAction
import com.intellij.openapi.application.WriteAction
import com.intellij.openapi.application.invokeLater
import com.intellij.openapi.fileEditor.FileEditorManager
import com.intellij.openapi.project.Project
import com.workflow.orchestrator.agent.tools.ToolResult
import com.workflow.orchestrator.agent.tools.psi.PsiToolUtils
import com.workflow.orchestrator.core.ai.TokenEstimator
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.contentOrNull
import kotlinx.serialization.json.jsonPrimitive

/**
 * `endpoints(action=export_http_scratch, filter?, host?)` — creates a
 * scratch `.http` file from discovered endpoints and opens it in the
 * editor. If the HTTP Client plugin is installed (Ultimate default),
 * the file has a "Run" gutter icon on each `###` block.
 *
 * Input params:
 *   filter — optional substring match against framework, url, or handler
 *   host   — optional base URL prefix (default: "http://localhost:8080")
 */
internal suspend fun executeExportHttpScratch(params: JsonObject, project: Project): ToolResult {
    if (PsiToolUtils.isDumb(project)) return PsiToolUtils.dumbModeError()

    val filter = params["filter"]?.jsonPrimitive?.contentOrNull
    val host = params["host"]?.jsonPrimitive?.contentOrNull ?: "http://localhost:8080"

    val endpoints = ReadAction.nonBlocking<List<DiscoveredEndpoint>> {
        EndpointsDiscoverer.discover(project)
    }.inSmartMode(project).executeSynchronously()

    val filtered = if (filter.isNullOrBlank()) endpoints else endpoints.filter {
        it.framework.contains(filter, ignoreCase = true) ||
            it.url.contains(filter, ignoreCase = true) ||
            (it.handlerClass?.contains(filter, ignoreCase = true) == true)
    }
    if (filtered.isEmpty()) {
        return ToolResult(
            content = "No endpoints matched${if (filter != null) " filter '$filter'" else ""}.",
            summary = "No endpoints to export",
            tokenEstimate = ToolResult.ERROR_TOKEN_ESTIMATE,
            isError = true,
        )
    }

    val body = buildString {
        appendLine("# Generated by Workflow Orchestrator — endpoints(action=export_http_scratch)")
        appendLine("# Edit host / headers / bodies as needed; run each block via the gutter icon.")
        appendLine()
        for (ep in filtered) {
            val method = ep.httpMethods.firstOrNull()?.uppercase() ?: "GET"
            val absoluteUrl = if (ep.url.startsWith("http")) ep.url else "$host${ep.url}"
            val handlerId = listOfNotNull(ep.handlerClass?.substringAfterLast('.'), ep.handlerMethod)
                .joinToString(".").ifEmpty { ep.url }
            val bodyPlaceholder = if (method in setOf("POST", "PUT", "PATCH")) "{}" else null
            append(renderHttpBlock(handlerId, method, absoluteUrl, bodyPlaceholder))
            appendLine()
        }
    }

    // Resolve the HTTP Client language if the plugin is installed; null falls back to plain text.
    val httpLanguage: Language? = Language.findLanguageByID("HTTP Request")
        ?: Language.findLanguageByID("HttpRequest")

    val scratchFile = WriteAction.computeAndWait<com.intellij.openapi.vfs.VirtualFile?, RuntimeException> {
        ScratchRootType.getInstance().createScratchFile(
            project,
            "workflow-endpoints.http",
            httpLanguage,
            body,
        )
    }
    if (scratchFile == null) {
        return ToolResult(
            content = "Scratch file creation failed (ScratchRootType returned null). " +
                "The generated .http content is included below.\n\n$body",
            summary = "Scratch file creation failed",
            tokenEstimate = TokenEstimator.estimate(body),
            isError = true,
        )
    }

    invokeLater {
        FileEditorManager.getInstance(project).openFile(scratchFile, true)
    }

    val summary = "Exported ${filtered.size} endpoint(s) to ${scratchFile.path}"
    return ToolResult(
        content = summary + "\n\n" + body,
        summary = summary,
        tokenEstimate = TokenEstimator.estimate(body),
    )
}
