import type { Config } from 'tailwindcss'

export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'ide-bg': 'var(--bg)',
        'ide-fg': 'var(--fg)',
        'ide-fg-secondary': 'var(--fg-secondary)',
        'ide-fg-muted': 'var(--fg-muted)',
        'ide-border': 'var(--border)',
        'ide-user-bg': 'var(--user-bg)',
        'ide-tool-bg': 'var(--tool-bg)',
        'ide-code-bg': 'var(--code-bg)',
        'ide-thinking-bg': 'var(--thinking-bg)',
        'badge-read-bg': 'var(--badge-read-bg)',
        'badge-read-fg': 'var(--badge-read-fg)',
        'badge-write-bg': 'var(--badge-write-bg)',
        'badge-write-fg': 'var(--badge-write-fg)',
        'badge-edit-bg': 'var(--badge-edit-bg)',
        'badge-edit-fg': 'var(--badge-edit-fg)',
        'badge-cmd-bg': 'var(--badge-cmd-bg)',
        'badge-cmd-fg': 'var(--badge-cmd-fg)',
        'badge-search-bg': 'var(--badge-search-bg)',
        'badge-search-fg': 'var(--badge-search-fg)',
        'accent-read': 'var(--accent-read)',
        'accent-write': 'var(--accent-write)',
        'accent-edit': 'var(--accent-edit)',
        'accent-cmd': 'var(--accent-cmd)',
        'accent-search': 'var(--accent-search)',
        'diff-add-bg': 'var(--diff-add-bg)',
        'diff-add-fg': 'var(--diff-add-fg)',
        'diff-rem-bg': 'var(--diff-rem-bg)',
        'diff-rem-fg': 'var(--diff-rem-fg)',
        'ide-success': 'var(--success)',
        'ide-error': 'var(--error)',
        'ide-warning': 'var(--warning)',
        'ide-link': 'var(--link)',
        'ide-hover': 'var(--hover-overlay)',
        'ide-hover-strong': 'var(--hover-overlay-strong)',
        'ide-divider': 'var(--divider-subtle)',
        'ide-row-alt': 'var(--row-alt)',
        'ide-input-bg': 'var(--input-bg)',
        'ide-input-border': 'var(--input-border)',
        'ide-toolbar-bg': 'var(--toolbar-bg)',
        'ide-chip-bg': 'var(--chip-bg)',
        'ide-chip-border': 'var(--chip-border)',
        'ide-accent': 'var(--accent)',
        'ide-running': 'var(--running)',
        'ide-pending': 'var(--pending)',
      },
      fontFamily: {
        body: ['var(--font-body)', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'sans-serif'],
        mono: ['var(--font-mono)', 'JetBrains Mono', 'Menlo', 'Consolas', 'Courier New', 'monospace'],
      },
      borderColor: {
        DEFAULT: 'var(--border)',
      },
    },
  },
} satisfies Config
