package com.workflow.orchestrator.agent.context

import com.intellij.openapi.diagnostic.Logger
import com.workflow.orchestrator.core.util.ProjectIdentifier
import kotlinx.serialization.Serializable
import kotlinx.serialization.encodeToString
import kotlinx.serialization.json.Json
import java.io.File
import kotlin.math.sqrt

/**
 * Long-term searchable memory using JSON-backed store with LLM-generated tags.
 *
 * At insert time, the caller provides tags (generated by the LLM) that bridge
 * the semantic gap — e.g., "EDT freeze" is tagged with ["crash", "freeze", "deadlock"].
 * At search time, keyword matching against both content and tags provides
 * relevance-ranked results without any ML models.
 *
 * Storage: `{projectBasePath}/.workflow/agent/archival/store.json`
 * Cap: [maxEntries] entries, oldest evicted when full.
 */
class ArchivalMemory(
    private val storePath: File,
    private val maxEntries: Int = 5000
) {
    companion object {
        private val LOG = Logger.getInstance(ArchivalMemory::class.java)
        private val json = Json { prettyPrint = false; ignoreUnknownKeys = true; encodeDefaults = true }
        private const val TAG_WEIGHT = 3 // Tags scored 3x vs content
        private val instanceCache = java.util.concurrent.ConcurrentHashMap<String, ArchivalMemory>()

        fun forProject(projectBasePath: String): ArchivalMemory {
            return instanceCache.getOrPut(projectBasePath) {
                val dir = File(ProjectIdentifier.agentDir(projectBasePath), "archival")
                dir.mkdirs()
                ArchivalMemory(File(dir, "store.json"))
            }
        }
    }

    @Serializable
    data class ArchivalEntry(
        val id: String,
        val content: String,
        val tags: List<String>,
        val type: String,          // "session_summary", "fact", "guardrail", "error_resolution", "agent_memory", "plan_outcome"
        val sessionId: String? = null,
        val timestamp: Long = System.currentTimeMillis()
    )

    @Serializable
    data class ArchivalStore(
        val entries: MutableList<ArchivalEntry> = mutableListOf(),
        var nextId: Int = 1
    )

    private var store = ArchivalStore()

    init {
        load()
    }

    /**
     * Insert a new entry with LLM-generated tags.
     * @param content The text to store
     * @param tags Searchable keywords (generated by LLM at insert time)
     * @param type Category of the entry
     * @param sessionId Optional session ID for provenance
     * @return The ID of the created entry
     */
    fun insert(content: String, tags: List<String>, type: String, sessionId: String? = null): String {
        val id = "arch-${store.nextId++}"
        val entry = ArchivalEntry(
            id = id,
            content = content.take(2000), // Cap content size
            tags = tags.map { it.lowercase().trim() }.filter { it.isNotBlank() }.take(20),
            type = type,
            sessionId = sessionId,
            timestamp = System.currentTimeMillis()
        )
        store.entries.add(entry)

        // Evict oldest if over limit
        while (store.entries.size > maxEntries) {
            store.entries.removeAt(0)
        }

        save()
        return id
    }

    /**
     * Search archival memory using keyword matching with tag boosting.
     *
     * Scoring: each query term scores 1 point for content match, [TAG_WEIGHT] for tag match.
     * Results are ranked by total score, filtered by minimum threshold.
     *
     * @param query Search query (space-separated terms)
     * @param topK Maximum results to return
     * @param typeFilter Optional filter by entry type
     * @return Ranked list of (entry, score) pairs
     */
    fun search(query: String, topK: Int = 5, typeFilter: String? = null): List<Pair<ArchivalEntry, Double>> {
        if (query.isBlank()) return emptyList()

        val queryTerms = query.lowercase().split(Regex("\\s+")).filter { it.length >= 2 }
        if (queryTerms.isEmpty()) return emptyList()

        val candidates = if (typeFilter != null) {
            store.entries.filter { it.type == typeFilter }
        } else {
            store.entries
        }

        return candidates
            .map { entry ->
                val contentLower = entry.content.lowercase()
                var score = 0.0

                for (term in queryTerms) {
                    // Content match via indexOf loop — O(n) per entry, not O(n*m) windowed
                    var contentMatches = 0
                    var searchFrom = 0
                    while (contentMatches < 3) { // Cap at 3 for scoring
                        val idx = contentLower.indexOf(term, searchFrom)
                        if (idx < 0) break
                        contentMatches++
                        searchFrom = idx + term.length
                    }
                    score += contentMatches.toDouble()

                    // Tag match (TAG_WEIGHT points per matching tag)
                    val tagMatches = entry.tags.count { tag ->
                        tag.contains(term) || term.contains(tag)
                    }
                    score += tagMatches * TAG_WEIGHT
                }

                // Normalize by query length so longer queries don't automatically score higher
                score /= sqrt(queryTerms.size.toDouble())

                entry to score
            }
            .filter { it.second > 0.5 } // Minimum relevance threshold
            .sortedByDescending { it.second }
            .take(topK)
    }

    /** Get total entry count. */
    fun size(): Int = store.entries.size

    /** Get entries by type. */
    fun getByType(type: String): List<ArchivalEntry> =
        store.entries.filter { it.type == type }

    /** Delete an entry by ID. Returns true if found and removed. */
    fun delete(id: String): Boolean {
        val removed = store.entries.removeAll { it.id == id }
        if (removed) save()
        return removed
    }

    /** Get all entries (for debugging). */
    fun getAll(): List<ArchivalEntry> = store.entries.toList()

    private fun load() {
        try {
            if (storePath.exists()) {
                store = json.decodeFromString<ArchivalStore>(storePath.readText())
            }
        } catch (e: Exception) {
            LOG.warn("ArchivalMemory: failed to load from ${storePath.name}", e)
            store = ArchivalStore()
        }
    }

    private fun save() {
        try {
            storePath.parentFile?.mkdirs()
            // Atomic write: write to temp file, then move atomically
            val tmp = File(storePath.parentFile, "${storePath.name}.tmp")
            tmp.writeText(json.encodeToString(store))
            java.nio.file.Files.move(
                tmp.toPath(), storePath.toPath(),
                java.nio.file.StandardCopyOption.REPLACE_EXISTING,
                java.nio.file.StandardCopyOption.ATOMIC_MOVE
            )
        } catch (e: Exception) {
            LOG.warn("ArchivalMemory: failed to save to ${storePath.name}", e)
        }
    }
}
