package com.workflow.orchestrator.agent.tools

import com.intellij.openapi.project.Project
import com.workflow.orchestrator.agent.api.dto.FunctionDefinition
import com.workflow.orchestrator.agent.api.dto.FunctionParameters
import com.workflow.orchestrator.agent.api.dto.ParameterProperty
import com.workflow.orchestrator.agent.api.dto.ToolDefinition
import kotlinx.serialization.json.JsonObject

/** Worker type for tool access control. Kept for compatibility with existing tools. */
enum class WorkerType {
    ORCHESTRATOR, ANALYZER, CODER, REVIEWER, TOOLER
}

/**
 * Payload for interactive React artifact rendered in the chat UI.
 *
 * [renderId] correlates the async render round-trip: Kotlin pushes the artifact to the
 * webview, the sandbox iframe renders it, then reports the outcome back via the
 * [ArtifactResultRegistry] bridge keyed by this id. Generated by [RenderArtifactTool].
 */
data class ArtifactPayload(
    val title: String,
    val source: String,
    val renderId: String,
)

/**
 * Outcome of rendering an interactive artifact in the sandbox iframe.
 *
 * Reported back from the webview via [ArtifactResultRegistry.reportResult]. The Kotlin
 * side of [RenderArtifactTool] awaits one of these (with a timeout) before returning a
 * [ToolResult], so the LLM sees actual render outcomes and can self-correct on failure
 * instead of the previous fire-and-forget "assumed success".
 */
sealed class ArtifactRenderResult {
    /** Sandbox rendered the component successfully. */
    data class Success(val heightPx: Int? = null) : ArtifactRenderResult()

    /**
     * Sandbox failed to render. [phase] is one of "transpile", "render", "runtime", "init".
     * [missingSymbols] contains identifiers the code referenced that were not in the sandbox
     * scope (parsed out of ReferenceError messages) — the primary signal for self-repair.
     */
    data class RenderError(
        val phase: String,
        val message: String,
        val missingSymbols: List<String> = emptyList(),
        val line: Int? = null,
    ) : ArtifactRenderResult()

    /** Iframe did not respond within the registered timeout. */
    data class Timeout(val timeoutMillis: Long) : ArtifactRenderResult()

    /**
     * No UI listener was registered at render time (e.g. headless tests or
     * a render_artifact call before the dashboard panel is constructed).
     * Tool treats this as optimistic success to preserve legacy behavior.
     */
    data class Skipped(val reason: String) : ArtifactRenderResult()
}

/** Simple token estimation: bytes / 4 (Codex CLI pattern, ~80% accurate). */
fun estimateTokens(text: String): Int = (text.toByteArray().size + 3) / 4

/**
 * Middle-truncate content keeping first 60% and last 40%.
 */
fun truncateOutput(content: String, maxChars: Int = 50_000): String {
    if (content.length <= maxChars) return content
    val headChars = (maxChars * 0.6).toInt()
    val tailChars = maxChars - headChars - 200
    val omitted = content.length - headChars - tailChars
    return content.take(headChars) +
        "\n\n[... $omitted characters omitted ...]\n\n" +
        content.takeLast(tailChars)
}

interface AgentTool {
    val name: String
    val description: String
    val parameters: FunctionParameters
    val allowedWorkers: Set<WorkerType>

    /** Max execution time in milliseconds. Default 120s. Override for tools needing more. */
    val timeoutMs: Long get() = DEFAULT_TOOL_TIMEOUT_MS

    /** Output configuration for this tool (max chars, truncation limits). */
    val outputConfig: ToolOutputConfig get() = ToolOutputConfig.DEFAULT

    suspend fun execute(params: JsonObject, project: Project): ToolResult

    fun toToolDefinition(): ToolDefinition = ToolDefinition(
        function = FunctionDefinition(
            name = name,
            description = description,
            parameters = parameters
        )
    )

    companion object {
        const val DEFAULT_TOOL_TIMEOUT_MS = 120_000L
        const val LONG_TOOL_TIMEOUT_MS = 600_000L  // 10 min for run_command, build, etc.

        /** Shared task_progress property injected into every tool schema at the API call site. */
        val TASK_PROGRESS_PROPERTY = ParameterProperty(
            type = "string",
            description = "A markdown checklist of plan progress (e.g. '- [x] Step 1\\n- [ ] Step 2'). " +
                "Include this when working through a plan to keep the progress widget updated."
        )

        /**
         * Inject task_progress into a tool definition's schema (Cline's FocusChain pattern).
         * Called at the API boundary so the LLM sees the parameter on every tool.
         */
        fun injectTaskProgress(def: ToolDefinition): ToolDefinition {
            val params = def.function.parameters
            if ("task_progress" in params.properties) return def
            return def.copy(
                function = def.function.copy(
                    parameters = params.copy(
                        properties = params.properties + ("task_progress" to TASK_PROGRESS_PROPERTY)
                    )
                )
            )
        }

        // ---- LLM-controlled output filtering parameters ----

        val GREP_PATTERN_PROPERTY = ParameterProperty(
            type = "string",
            description = "Regex pattern to filter output lines. Only lines matching this pattern are returned. " +
                "Use when you only need specific information from a potentially large output."
        )

        val OUTPUT_FILE_PROPERTY = ParameterProperty(
            type = "boolean",
            description = "If true, save full output to a file and return a preview with the file path. " +
                "Use for large outputs you may need to search later. Read the file with read_file or search_code."
        )

        /** Set of tools that support output filtering parameters. */
        val OUTPUT_FILTERABLE_TOOLS = setOf(
            "run_command", "search_code", "git", "sonar",
            "bamboo_builds", "bamboo_plans", "jira", "db_query",
            "bitbucket_pr", "bitbucket_repo",
        )

        /**
         * Inject grep_pattern and output_file parameters into a tool definition.
         * Only applied to tools in [OUTPUT_FILTERABLE_TOOLS].
         */
        fun injectOutputParams(def: ToolDefinition): ToolDefinition {
            if (def.function.name !in OUTPUT_FILTERABLE_TOOLS) return def
            val params = def.function.parameters
            if ("grep_pattern" in params.properties) return def
            return def.copy(
                function = def.function.copy(
                    parameters = params.copy(
                        properties = params.properties +
                            ("grep_pattern" to GREP_PATTERN_PROPERTY) +
                            ("output_file" to OUTPUT_FILE_PROPERTY)
                    )
                )
            )
        }
    }
}

data class ToolResult(
    val content: String,
    val summary: String,
    val tokenEstimate: Int,
    val artifacts: List<String> = emptyList(),
    val isError: Boolean = false,
    val isCompletion: Boolean = false,
    val verifyCommand: String? = null,
    /** True when this result is a plan_mode_respond output (plan presentation). */
    val isPlanResponse: Boolean = false,
    /** True when the LLM needs more exploration before finalizing the plan. */
    val needsMoreExploration: Boolean = false,
    /** Structured plan step titles provided by the LLM via plan_mode_respond. */
    val planSteps: List<String> = emptyList(),
    /** True when this result activates a skill via use_skill tool. */
    val isSkillActivation: Boolean = false,
    /** The skill name that was activated (set by UseSkillTool). */
    val activatedSkillName: String? = null,
    /** The full skill content that was loaded (set by UseSkillTool). */
    val activatedSkillContent: String? = null,
    /**
     * True when this result signals a session handoff via new_task tool.
     * Ported from Cline: the LLM creates a structured context summary and
     * hands off to a fresh session to escape context exhaustion.
     */
    val isSessionHandoff: Boolean = false,
    /**
     * The structured handoff context for the new session.
     * Contains: Current Work, Key Technical Concepts, Relevant Files and Code,
     * Problem Solving, Pending Tasks and Next Steps.
     */
    val handoffContext: String? = null,
    /**
     * Unified diff for file changes (edit_file, create_file).
     * Sent to the UI for before/after diff display.
     */
    val diff: String? = null,
    /** True when the LLM requests switching to plan mode via enable_plan_mode tool. */
    val enablePlanMode: Boolean = false,
    /** Interactive React artifact to render in the chat UI (set by RenderArtifactTool). */
    val artifact: ArtifactPayload? = null
) {
    companion object {
        const val ERROR_TOKEN_ESTIMATE = 5

        fun error(message: String, summary: String = message): ToolResult =
            ToolResult(message, summary, ERROR_TOKEN_ESTIMATE, isError = true)
    }
}
